### ISSUE TITLE
Improve the pages when signing up.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#138]
When users signup on the Me App for the first time they have to finish the signup flow. In some of the screens the user doesn't have the option to go back. Every page should have an option to go back, just like the first page. 

This way people can change their information if they made a mistake or typo.

--------------------------------

![img_0019](https://user-images.githubusercontent.com/38419514/46999969-7021e780-d127-11e8-9cd7-13e2059e95c4.PNG)
![img_0020](https://user-images.githubusercontent.com/38419514/46999970-7021e780-d127-11e8-8987-fe64eb4eb048.PNG)
![img_0021](https://user-images.githubusercontent.com/38419514/46999971-70ba7e00-d127-11e8-86ad-d2b9f2e97278.PNG)
![img_0022](https://user-images.githubusercontent.com/38419514/46999972-70ba7e00-d127-11e8-8bba-4e6f584b70d8.PNG)

**Comment by jknnr** [comment]
those steps now are hidden, so the user can set up all of those in the profile, so I am closing this issue as a non relevant
