### ISSUE TITLE
Empty "succes" page after clicking the link send by e-mail ("I already have an identity")

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#141]
1. If the user clicks on the link that has been send to it's e-maill adress, it gets redirected to a empty page with a "succes" message.

--------------------------------

1. Would be nice if the page would be more in the style of the Forus brand identity.
2. Add a notification for further guidelines

	- English: "Please open the Me App to log in"
	- Dutch: "Open de Me App om in te loggen"

**Comment by jknnr** [comment]
fixed
