### ISSUE TITLE
Add confirmation notifications after validation

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#142]
There are missing some confirmations after the validator validates a record.

1. No confirmation at QR-Code scanner after validator validates te record.
2. No confirmation at the identity where the record is approved. (so the requester doesn't get any notification after validation.

--------------------------------

1. Add confirmation at the QR-Code scanner screen after validation. 	
	- Dutch: "Validatie geslaagd!"
	- English: "Validation successful!"

2. Add confirmation at the identity where the record is validated.

	- Dutch: "Er is een eigenschap gevallideerd!"
	- English: "A record has been validated!"

**Comment by maxvisser** [comment]
I will close this for. Validations is not actively being worked on.
