### ISSUE TITLE
When clicking 'Mail to myself' don't show input field of mail address

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#143]
**Is your feature request related to a problem? Please describe.**
When at the voucher details page you have to option to send the voucher to your mail. It now gives you a input field to enter your mail adress

**Describe the solution you'd like**
We already know the person's email adress and they should not be able to send it to a different email than themselves. The user should get a confirm screen that the voucher has been send to their e-mail instead of a input screen.

also the button now says ' VERSUTERN', this should be 'VERSTUREN'

**Comment by maxvisser** [comment]
As I know you can just send identity address (0xaa) and QR url to endpoint /nl/sender/vouchers/sended_via_email would be nice to do this via backend for security reasons though

**Comment by jknnr** [comment]
Fixed
