### ISSUE TITLE
Show expire date of product voucher on product voucher details page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#144]
**Is your feature request related to a problem? Please describe.**
A fund does not yet have a expire date but a product does. 

**Describe the solution you'd like**
Implement a day count till the day the product voucher expires

**Comment by jknnr** [comment]
Yesterday got message from Valentin that we can not implement it yet. Will find out why and comment

**Comment by maxvisser** [comment]
Valentin also just told me its not implemented (luckily) will close this for now.
