### ISSUE TITLE
change Voucher Info to 'Provider Info' on product voucher

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#145]
**Is your feature request related to a problem? Please describe.**
As voucher info now leads to zuidhorn.forus.io on a product,

**Describe the solution you'd like**
 It would be better to send the user to a page where he can see the product, where the provider is located.
https://[env].zuidhorn.forus.io/#!/products/[product_id]

**Comment by danieltcacenco** [comment]
Done
