### ISSUE TITLE
Instead of showing transaction on the productvoucher show provider details

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#146]
**Is your feature request related to a problem? Please describe.**
A productvoucher currently has like a normal voucher transactions. This is useless information because there will only be one transaction on a product voucher.

**Describe the solution you'd like**
Show provider details and map of where the provider is located.

**Comment by jknnr** [comment]
good one!

**Comment by jknnr** [comment]
https://app.zeplin.io/project/5b2b54cc846eb4ef0d743133/screen/5bfc662c58e4013ea476b849
<img width="296" alt="screen shot 2018-11-27 at 10 17 49" src="https://user-images.githubusercontent.com/32199937/49071197-bb9ed980-f22d-11e8-9bc0-34263bfaffeb.png">

**Comment by jknnr** [comment]
done
