### ISSUE TITLE
Me-android translations

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#149]
**Is your feature request related to a problem? Please describe.**
Some things are not translated yet. List:
Use fingerprint
About
App version
Email to me

**Describe the solution you'd like**
Use fingerprint - Gebruik vingerafdrukscanner
About - Over Me
App version - App versie
Email to me - E-mail naar mijzelf

**Wrong translations**
Under a transaction in the transaction overview it says 'betaling'  this should be 'betaald'
All mentions of 'Identiteit' should be changed to 'Profiel'

**Comment by jknnr** [comment]
done
