### ISSUE TITLE
Voucher does not show product transactions

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#151]
## Prerequisites

Already have a voucher with product transaction on dev.
Download Me 0.0.5-dev-release
login via mail on Me android
Click on your voucher where you already have transactions on.

## Description

![photo_2018-11-07_11-28-30](https://user-images.githubusercontent.com/10818702/48125947-3b193880-e280-11e8-81c4-83ac9fe6d368.jpg)

![photo_2018-11-07_11-28-27](https://user-images.githubusercontent.com/10818702/48125952-3ce2fc00-e280-11e8-890f-138833bcaef5.jpg)

**Comment by maxvisser** [comment]
Transactions on productvouchers work though.

**Comment by maxvisser** [comment]
Seems that the voucher does not have any 'real' transactions only products were bought with the voucher.

**Comment by jknnr** [comment]
fixed
