### ISSUE TITLE
Hide open on me button on mobile

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#152]
## Context
User click on 'Login via Mail' in Me-app and gets mail that contains a link. This link will open:
![image](https://user-images.githubusercontent.com/10818702/61636992-07a7fe00-ac97-11e9-84df-27d504aad417.png)

When clicked on button Me-app opens. This page will have a second button for people who are on Desktop.
First button will redirect to App.
Second button will authenticate app while on desktop.

**Comment by jamalv** [comment]
I think this page doesn't need a design. When you land on this page, the action should be triggered that is now after clicking the button > you should be immediately redirected without interruption.

**Comment by maxvisser** [comment]
What do you want to do with the second button? If people will open the link on desktop.

**Comment by jamalv** [comment]
On mobile it should be hidden, on desktop it should open the solution we are currently working on: https://github.com/teamforus/me/issues/380
