### ISSUE TITLE
Some changes when scanning voucher as a provider.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#163]
## Context/goal: 

- Change title from: "Bevestig verzoek" to "Bevestig betaling" (**EN** : Confirm transaction)
- Change the price to a sentence: Instead of €30,? make it: Klopt het bedrag van €30,00? (**EN**: Is the price of €30,00 correct?)
- Change button text to: "BEVESTIG" (**EN**: Confirm)

![img_1c573dd009d4-1](https://user-images.githubusercontent.com/38419514/48474816-ab353a80-e7fb-11e8-8479-2f2881a9fefd.jpeg)

**Comment by maxvisser** [comment]
I think the correct information is in Android already, please don't think up new text (that would mean more inconsistencies)

**Comment by maxvisser** [comment]
@jknnr can  you check if this is fixed and close it?
