### ISSUE TITLE
Setting up different targets.

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#165]
We currently have different environments and build targets. This issue is meant to clarify the specs, discuss and implement.

We will discern the apps by having different build configs, with different [BundleID's and icons](http://nilsou.com/blog/2013/07/29/how-to-have-two-versions-of-the-same-app-on-your-device/) and that connect to different environments. We follow [this branching strategy](https://nvie.com/posts/a-successful-git-branching-model/).

## Production
**repo branch:** master
**api baseURL:** https://api.forus.link/api/v1/\(url)
**app bundleID:** io.forus.me
**deployment iOS:** App Store
**deployment Android:** Play Store

## Demo (beta testing)
**repo branch:** master
**api baseURL:** https://demo.api.forus.io/api/v1/\(url)
**app bundleID:** io.forus.me.beta
**deployment iOS:** TestFlight (external, [public link](https://testflight.apple.com/join/gWw1lXyB))
**deployment Android:** Google Play Console

## Staging (alpha testing)
**repo branch:** staging
**api baseURL:** https://staging.api.forus.io/api/v1/\(url)
**app bundleID:** io.forus.me.alpha
**deployment iOS:** TestFlight (internal) {no review is needed here}
**deployment Android:** Google Play Console

## Features (development and local testing)
**repo branch:** feature/featurename
**api baseURL:** http://localhost/\(url)
**app bundleID:** io.forus.me.local
**deployment iOS:** Direct installation
**deployment Android:** Direct installation

## Develop
**repo branch:** develop
**api baseURL:** https://dev.api.forus.io/api/v1/\(url)
**app bundleID:** io.forus.me.dev
**deployment iOS:** Direct installation
**deployment Android:** Direct installation

**Comment by jamalv** [comment]
On iOS, this will mean we will have three apps in iTunes connect:

<img width="928" alt="screenshot 2018-11-15 at 14 20 41" src="https://user-images.githubusercontent.com/30194799/48556740-10b12600-e8e5-11e8-92f4-aea31033eab1.png">

One that is connected to the App Store, one that is used for alpha testing (internal), and one that is used for beta testing (external).

@jknnr @Myshelova I heard you are working on different app icons?

Would be awesome if we could do something like this: 
<img width="303" alt="screenshot 2018-11-15 at 14 48 52" src="https://user-images.githubusercontent.com/30194799/48556923-959c3f80-e8e5-11e8-8b26-c4c3d2d51d6f.png">

So that means three different icons:
* Production (the one we have)
* Alpha
* Beta

Kinda like the one above, but then with "alpha" and "beta" labels / ribbons

**Comment by jknnr** [comment]
Let's do it!

**Comment by jknnr** [comment]
During the discussion we thought to use not labels but colours and opacity gradation for versioning. 
Labels are more associated with sales, or saying "free" to motivate you to buy the full version. With the colours we can make logical patterns, like grey(alpha)-->light blue(beta)-->normal blue(prod), or even make a development yellowish. I will give an example below:

**Comment by jknnr** [comment]
![photo_2018-11-15_23-18-47](https://user-images.githubusercontent.com/32199937/48585401-d53a4a00-e92c-11e8-9837-b6ea5ca7fef6.jpg)

**Comment by jknnr** [comment]
<img width="476" alt="2018-11-16 0 47 16" src="https://user-images.githubusercontent.com/32199937/48585449-fa2ebd00-e92c-11e8-9bc9-c3e3803fd7a6.png">

**Comment by maxvisser** [comment]
@jamal i would recommend using staging for alpha testing the apps and demo for beta testing for now. As we discussed this is better for the release cycle.

**Comment by GerbenBosschieter** [comment]
@jknnr I've searched how we can accomplish this in Google Playstore Console. We can align it with Appleconnect. So let's implement this.

**Comment by maxvisser** [comment]
@GerbenBosschieter Could you write what you found and explain it to yasha? @jamalv will do the same for iOS, so yasha could do it himself :+1:

**Comment by jamalv** [comment]
Jup! I do think the text labels are important, otherwise it might be difficult for people to see the difference.

**Comment by jknnr** [comment]
[icon_android.zip](https://github.com/teamforus/me/files/2603761/icon_android.zip)
[icon_ios.zip](https://github.com/teamforus/me/files/2603762/icon_ios.zip)

**Comment by jknnr** [comment]
Icons with labels were implemented, builds & environments were explained. Now should be clear

**Comment by danieltcacenco** [comment]
Done

**Comment by ukakhmedoff** [comment]
done
