### ISSUE TITLE
Empty Authorisation code

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#167]
Sometimes the authorisation code shows no numbers.

## Steps to Reproduce (bug report)
From welcome screen click "I Already Have an Identity", then see the code.

**Expected behavior:** 
Show the code
**Actual behavior:**
Sometimes code is not shown
**Reproduces how often:** 
10%

![image-1](https://user-images.githubusercontent.com/32199937/48634349-afad4f00-e9c5-11e8-9c4f-4824aa7ef096.jpg)

**Comment by jknnr** [comment]
@danieltcacenco told me that it is something that comes from the backend, like a wrong format of code or error. @danrminds will you check with Valik?

**Comment by maxvisser** [comment]
If this only happens on iOS I can't see it be the backend.

**Comment by maxvisser** [comment]
@danieltcacenco can you explain a bit more here?

**Comment by jknnr** [comment]
happens only when bad internet connection, closing it
