### ISSUE TITLE
voucher info on normal voucher remove or adjust

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#170]
## Context/goal: 
It now leads to zuidhorn.forus.io;
should lead to zuidhorn or nijmegen depending on implementation 
or should be removed

**Comment by jknnr** [comment]
requested some backend adjustments from Valentin

**Comment by maxvisser** [comment]
can you add this to an issue in forus? instead of asking @dev-rminds directly, so I can also see it :)

**Comment by dev-rminds** [comment]
Backend part is ready

**Comment by jknnr** [comment]
(branch feature-voucher-url-webshop)

**Comment by jknnr** [comment]
done
