### ISSUE TITLE
Receive device info when the app crashes

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#174]
**Is your feature request related to a problem? Please describe.**
When we receive a crash on Crashlytics it is impossible to know which device and which user had it, so the support has to guess or call every shopkeeper to find out what was wrong. Most of the time it happens because shopkeepers use older version of the app.

**Describe the solution you'd like**
It would be awesome to receive the device identifier to track where the crash happened and communicate directly with the shopkeeper

**Comment by maxvisser** [comment]
can we catch the crash and ask to send the device info to developers? or can this only be implemented without consent of user.

**Comment by pantyukhov** [comment]
@jknnr What will we do with this task?

**Comment by jknnr** [comment]
we will ask the user if he wants to send us bug-reports with his direct contact

**Comment by maxvisser** [comment]
@danieltcacenco does this need to be configured again?

**Comment by danieltcacenco** [comment]
no we already have such function in fabric.io if it happens some crash we get those error and we can fix it, also if user enable address of user in this case we will now what user get some crash.

**Comment by maxvisser** [comment]
Thanks!
