### ISSUE TITLE
Organisation context

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#175]
## **Is your feature request related to a problem? Please describe.**
Because we want the user to be able to identify himself as a organisation in Me for looking at transaction we need the organisation context switch.

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/10818702/49099462-cda26b80-f271-11e8-94b7-8eab111d8d0e.png)

**content NL**
Title Wissel van context
Namens organisatie
{{ name of organisation }}
Namens jezelf
{{ full name or personal email }}

**content EN**
Title: Switch context
on behalf of organization
{{ organisation name }}
on behalf of yourself
{{ full name or personal email }}

## hide context switch if not applical
If you only have one context. We should hide it.

**Comment by jknnr** [comment]
design is done
