### ISSUE TITLE
Pressing the back button on android takes me back to the ¨welcome to me¨ page

### ISSUE THREAD

**Issue by maartenfv** [teamforus/me#180]
#96 has been closed but has not yet been fixed. Whenever I am logged into the app and I press the back button to many times the app still logs me out. I need to use the email recovery method to get back into the app.

This issue can be closed when the app does not allow me to ¨log-out¨ or go back to the welcome screen by pressing back.

**Comment by jknnr** [comment]
Hmmm its a lil bit strange, doesn't happen on our test device. When you press back it just closes the app, but you stay logged in. I will test the latest version on your phone tomorrow!

**Comment by jknnr** [comment]
The bug can not be reproduced so far, will keep this issue in the icebox unless someone will request again

**Comment by maxvisser** [comment]
Lets close it for now.
