### ISSUE TITLE
QR-code scanning, fake success message.

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#183]
Example:
If I have my app connected to staging, and I scan some qr code on the production environment, like logging with the app on the websop, after scanning the qr-code, the pop-up gives me successful message, but the login is not happening (obviously)

Solution: 
Give an error message when this happens

**Comment by GerbenBosschieter** [comment]
Wasn't this problem only when you scan a voucher with on a different environment.  So in no user experience this will really happen right?

**Comment by maxvisser** [comment]
Well as I understand it can happen if the auth code in the QR code is not valid anymore.

**Comment by danieltcacenco** [comment]
I was discuss about that with Valentine and he say to make that we must to change the qr code structure.

**Comment by jknnr** [comment]
So currently we implemented the error "unknown qr-code" 
I am closing this issue
