### ISSUE TITLE
After pressing email to me, first show the dialog (popup)

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#186]
**Is your feature request related to a problem? Please describe.**
Sometimes I press the button by mistake and it sends the voucher immediately. Would be nice if it first asked for confirmation.

Texts:
NL: Stuur de voucher naar uw e-mailadres?
EN: Send the voucher to your email?

Buttons:
NL: Stuur - Annuleer
EN: Send - Cancel

**Comment by jknnr** [comment]
@ukakhmedoff change text on the message please
NL: Wilt u ons verbeterpunten per mail versturen ?
EN: Would you like to send us your feedback by e-mail?
Buttons text is the same

**Comment by danieltcacenco** [comment]
Done

**Comment by ukakhmedoff** [comment]
done
