### ISSUE TITLE
Change text success message

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#190]
## Main asssignee: @ukakhmedoff 
When the voucher was sent by mail, the success message should show the following text:
NL: De voucher is verzonden per mail
EN: The voucher was sent to your mail

<img width="678" alt="screen shot 2018-12-05 at 11 42 31" src="https://user-images.githubusercontent.com/32199937/49508495-229e3d00-f883-11e8-9832-95db7c6ad918.png">

**Comment by ukakhmedoff** [comment]
done

**Comment by jknnr** [comment]
done
