### ISSUE TITLE
Alcatel Pixi 4 support

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#196]
## Context/goal: 
we bought a alcatel pixi 4 and wanted to download 'Me' on android. The app store says the app is not compatible for this device. 

I researched it a bit and we should add supported screens to android manifest and maybe delete autofocus as used feature (if not needed).
```
<supports-screens 
    android:resizeable="true"
    android:smallScreens="true" 
    android:largeScreens="true"
    android:xlargeScreens="true"  
    android:normalScreens="true" 
    android:anyDensity="true"/>
```
We side loaded the app on the phone and it worked great. (pretty fast even for a phone worth 35 euros)

**Comment by jknnr** [comment]
why did you buy this phone guys? :D

**Comment by maxvisser** [comment]
i want to give some props to devs of me android. the app works better than the launcher on this phone. the launcher lags like all the time. But _Me_ is smooth like butter.

**Comment by jknnr** [comment]
still have no answer except for it's the device problem. I can add #wontfix label or just close it. @maxvisser would like to know what you think

**Comment by maxvisser** [comment]
I want to keep it open. :) I think we can find a solution.

**Comment by GerbenBosschieter** [comment]
yes, testing it right now. The Nokia 1 is confirmed. pixie we can download but not confirmed yet that we can do a transaction

**Comment by maxvisser** [comment]
the BUNQ app for android also works on the pixi btw.

**Comment by GerbenBosschieter** [comment]
pixie confirmed, everything is working

**Comment by jknnr** [comment]
yeey good job!
