### ISSUE TITLE
text fingerprintscanner fix

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#199]
### title
NL 'Ontgrendel Me'
EN: 'Unlock Me'

### description
NL: De app is vergrendeld met een vingerafdruk ingesteld in de instellingen van dit apparaat. Gebruik uw vingerafdrukscanner om Me te ontgrendelen.
EN: You can unlock Me using your fingerprint set in the setting of your mobile device. Please use your fingerprintscanner to scan your fingerprint to unlock Me.

### Below icon
NL: Bevestig vingerafdruk om te ontgrendelen.
EN: Confirm fingerprint to unlock

### button text change
Button 'cancel' should be change to 'Use passcode'
Button 'Annuleer' should be change to 'Gebruik inlogcode'

**Comment by jknnr** [comment]
done
