### ISSUE TITLE
changing passcode subtitles

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#200]
### Enter old inlogcode
title: Vul je bestaande inlogcode in
Subtitle: Om je inlogcode te wijzigen hebben vul je je bestaande inlogcode in.

## Enter new passcode
Title: Vul je nieuwe inlogcode in
Subtitle: Beveilig je profiel door een inlogcode aan te maken.

## Confirm new passcode
Title: Bevestig inlogcode
Subtitle: Herhaal je inlogcode om hem te bevestigen

**Comment by jknnr** [comment]
done
