### ISSUE TITLE
text below QR-code

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#207]
## Context/goal: 
'Dit is je persoonlijke QR-code' is wrong should be 
'Dit is uw 'fund_name'-voucher in de vorm van een QR-code'

on android it only saying 'scan this QR-code' please also change to 
'Dit is uw 'fund_name'-voucher in de vorm van een QR-code'

## information
maybe add information button to explain the interaction. You have this QR-code you can go to approved provider to buy their offers.

**Comment by danieltcacenco** [comment]
We can make some popup for that with explanation about qr code.

**Comment by ukakhmedoff** [comment]
done

**Comment by jknnr** [comment]
done
