### ISSUE TITLE
productvoucher info should go to product page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#208]
## Context/goal: 
Voucher Info button should got to {{webshop implementation}}/product/{id}

**Comment by danieltcacenco** [comment]
You can't do that because you must to be log in on webshop also from mobile.

**Comment by jknnr** [comment]
@maxvisser what do you think?

**Comment by maxvisser** [comment]
these pages are accessible without login.

**Comment by maxvisser** [comment]
https://staging.zuidhorn.forus.io/products/13

**Comment by jknnr** [comment]
done
