### ISSUE TITLE
Peer-to-peer identification / communication

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#21]
![34671005-f329d714-f478-11e7-8c19-968ae55fdf6a](https://user-images.githubusercontent.com/30194799/37329210-1a899320-269d-11e8-8a17-3bfa13b34c2d.png)

**Comment by maxvisser** [comment]
Instead of using IPNS. We can use something like Orbit-db. The app creates a new open remote database and shows the address for the public database.  After that it listens to the channel. 

The app Me scans the address and writes an documentDB JSON file with pk and ecrypted token to the database.

**Comment by maxvisser** [comment]
I think we should add this issue to R&D repo; @jamalv do you agree?

**Comment by jamalv** [comment]
Jup agreed, this issue is superseded by: https://github.com/teamforus/research-and-development/issues/96
