### ISSUE TITLE
Update App Store screenshots / marketing material

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#212]
<img width="1007" alt="screenshot 2018-12-18 at 08 26 16" src="https://user-images.githubusercontent.com/30194799/50138362-aa7e4100-029e-11e9-99b0-5a027ecb1c10.png">

We should use more international names in the screenshots "e.g. John Do" and I think by now we can show better eye candy. Also the order should be updated, the first image now is not very pleasing. Especially since there is a typo.

**Comment by maxvisser** [comment]
Is this not yet fixed?!?

**Comment by jknnr** [comment]
fixed
