### ISSUE TITLE
Nokia 1 - Support

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#214]
## Context/goal: 
Please research the possibility if the Me-app can support a Nokia 1.
We gave the advice to the municipality to buy a couple Nokia 1 phones for all the provider who are missing a phone so they can use the Me-app.

I already got a support case where someone is mentioning the phone is not compatible.

**Comment by jknnr** [comment]
Ive been checking this phone already! Seems to be fine to me, will ask Usman and Pasha

**Comment by jknnr** [comment]
done
