### ISSUE TITLE
Crash: open login link that has been used already

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#216]
## Prerequisites

1. Me app on iOS (build currently in App Store 26-12-2018)
2. Login using a login url
3. Log out

## Description

You can make the app crash by using an already used login email. Sometimes users will get confused and will get in this situation. (if they try to open the link in an old email)

## Steps to Reproduce (bug report)

1. Use the same login url that's already been used to login in again. (screen recording attached below)

**Expected behavior:** You get an error stating: this link has expired, please check your email for a new link.

**Actual behavior:** Crash

[ScreenRecording_12-26-2018 12-00-43.mp4.zip](https://github.com/teamforus/me/files/2710113/ScreenRecording_12-26-2018.12-00-43.mp4.zip)

**Comment by jknnr** [comment]
fixed
