### ISSUE TITLE
Bug when not allowing camera access, get logged out

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#217]
## Reproduce:
Can be done in two ways: 
1. Do a clean install of the me app on iOS. When opening the QR scanner for the first time it will ask for camera access. Deny it. Then it says you need the camera. Press cancel.
2. If app is already installed, go to iOS settings > me > turn camera access off. (this setting is persistent) Delete the me app from your device. Install again from the App Store. Login trough email. Open the QR-scanner. Click cancel. You will be logged out.

**Comment by jknnr** [comment]
fixed
