### ISSUE TITLE
Transaction information is not correct.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/me#219]
As can be seen in the screenshot below the transaction information (time/date) stays the same for each transaction.

![screenshot_20181227-111437_me](https://user-images.githubusercontent.com/30211022/50476715-7951ef00-09c9-11e9-9351-aa1276a6809d.jpg)

**Comment by maxvisser** [comment]
shows creation date time of voucher instead of transaction date time

**Comment by pantyukhov** [comment]
I think it cat happen when transaction hasn't date/time

**Comment by pantyukhov** [comment]
Done
