### ISSUE TITLE
Demo login doesn't work

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#22]
## Prerequisites

1. iOS or Android app me
2. kindpakket.dev-rminds.nl

## Description

Logging in to the kifndpakket demo by scanning the qr code doesn't work (tested on iOS and Android)

## Steps to Reproduce (bug report)

1. Sign up in the demo app
2. Click 'log me in' on the kindpakket site
3. Scan the code

**Expected behavior:** Log in

**Actual behavior:** Doesn't log in

**Reproduces how often:** 90% of the time, did work once on iOS

**Comment by jamalv** [comment]
tried on both chrome and safari, wifi and hotspot, no luck.

My console (chrome:

<img width="1630" alt="screen shot 2018-03-15 at 10 29 54" src="https://user-images.githubusercontent.com/30194799/37454828-e299612a-283b-11e8-81dd-c041c82a3b19.png">

**Comment by danrminds** [comment]
Can you please make a screenshot from:

Network -> XHR -> press login. And wait for the error to appear.

**Comment by jamalv** [comment]
<img width="1627" alt="screen shot 2018-03-15 at 10 36 44" src="https://user-images.githubusercontent.com/30194799/37455202-d40a6676-283c-11e8-8b39-0d52917d0523.png">

**Comment by danrminds** [comment]
Okay, thank you. Seems to be something related to what we had at the Common Ground. Will look what else can be wrong

**Comment by danrminds** [comment]
@jamalv Can we close this issue after the last fix? did the error appear since then?

**Comment by jamalv** [comment]
this has been fixed
