### ISSUE TITLE
add message when backend is in maintenance mode

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#220]
## Context/goal: 

When api gives back a 503 error we should show a message. 'Currently maintenance is being done'
NL: 'Me - Forus is onbereikbaar voor gepland onderhoud.'

Status Code: 503 Service Unavailable

## Task
- [ ] reproduce bug
- [ ] fix issue

**Comment by GerbenBosschieter** [comment]
@danieltcacenco almost!
I can see a message but because the app can't load any information the loading animation is in a loop and blocks the message. See image below

![image](https://user-images.githubusercontent.com/38419514/60952377-6f576400-a2fb-11e9-92ed-6b2b43de8ad9.png)

**Comment by maxvisser** [comment]
needs to be tested again

**Comment by maxvisser** [comment]
I will close this issue and will create a CR to make a good maintenance mode. (test for example database errors etc how will this impact users)
