### ISSUE TITLE
Responsiveness: Improve Me-app for smaller screens.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#221]
## Context/goal: 
Some screens of the Me-app are not compatible with smaller devices like the Samsung Galaxy J5 or our Alcatel pixie.

**Example**
The screen where people can choose how to log in (so the screen with the authorization code) gets cut off. People see only 5 digits instead of 6. So they cannot connect their profile to the app.

**Comment by maxvisser** [comment]
Main problem for now is the authorisation code as it breaks the signupflow for providers.

**Comment by GerbenBosschieter** [comment]
Yea I've should have make this issue smaller and more concrete. Problem with auth code is done. Will close this issue. Will make separate issues for every responsiveness issue
