### ISSUE TITLE
GoogleMaps ProductVoucher doesn't seem to work.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#223]
## Prerequisites

1. Me - profile with a product voucher
2. Me app

## Description
If I open a product voucher in the me app it will give me the google maps section.
But there is no information in this block and on the left corner it only says Google, no coordination, no marker, no map.

**Expected behavior:** [What you expect to happen]
A google maps section with the correct information

**Actual behavior:** [What actually happens]
A google maps section without any info

**Reproduces how often:** [What percentage of the time does it reproduce?]
all the time

**Comment by jknnr** [comment]
done
