### ISSUE TITLE
Warning when no mailservices available

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#233]
## Context/goal: 
*

**Comment by maxvisser** [comment]
![sigdysko](https://user-images.githubusercontent.com/10818702/51325448-371e4980-1a6d-11e9-8e68-3fd5d757c9cb.jpeg)

Title: Waarschuwing
Text: U heeft geen mail-app ingesteld op uw apparaat.

**Comment by jknnr** [comment]
done
