### ISSUE TITLE
Over Me

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#234]
## Context/goal: 

Title: Over Me
Description:
Deze app is bedoelt om vouchers te heren, betalingen te verrichten en in te loggen op verschillende applicaties.

Deze app werkt samen met:

- de Nijmegen webshop
- de Westerkwartier webshop
- de Forus generieke webshop

Later zullen meerdere shops en andere applicaties worden toegevoegd.

INGLESH:

Title: About Me
Description:
This app is intended to store vouchers, make payments and log in to different applications.

This app works together with:

- the Nijmegen webshop
- the Westerkwartier webshop
- the Forus generic webshop

Later on several shops and applications will be added.

**Comment by jknnr** [comment]
@maxvisser do you think we need feedback button there? We have it right after the Over Me thing in the profile
I would prefer not making it again inside of the the screen

**Comment by maxvisser** [comment]
could also just put the mail adres there.

**Comment by jknnr** [comment]
done

**Comment by jknnr** [comment]
Now it looks poor. Need to redesign.

**Comment by maxvisser** [comment]
Redesign?

**Comment by jknnr** [comment]
This will stay in ice-box, but yes, we can make it look better with this content. I just commented to remember after some time:)
