### ISSUE TITLE
When doing a transaction of 0,01 cent I get an error

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#235]
## Context/goal: 
I get an error (in english) that the amount is too low. 

## Task 
- [ ] implement warning:
Title: 'Waarschuwing'
Description: 'Een betaling van €0,01 is te laag om uit betaald te worden, kies een hoger bedrag.'

**Comment by jknnr** [comment]
On android it says transaction failed, that is also not right. We need to make a new separate error for this from the server.

**Comment by jknnr** [comment]
So when the sum is lower that 0,1 - we get an error smth like the amount you entered is too small

**Comment by maxvisser** [comment]
Should be intended if that the case. As bunq transaction costs are 10 cents

**Comment by maxvisser** [comment]
@danieltcacenco the message for this error should be changed 
Title: 'Waarschuwing'
Description: 'Een betaling van €0,01 is te laag om uit betaald te worden, kies een hoger bedrag.'

**Comment by GerbenBosschieter** [comment]
tested it, not done yet.

**Comment by maxvisser** [comment]
can't be tested as there is another bug that prevents filling in 0,01 cents (localisation issue with keyboard)

**Comment by maxvisser** [comment]
still wrong text on build 10

**Comment by maxvisser** [comment]
Done
