### ISSUE TITLE
Marquee on long titles on voucher

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#236]
## Context/goal: 
When a title of a product or fund is too long we now marquee the text 

https://developer.mozilla.org/nl/docs/Web/HTML/Element/marquee#Voorbeelden

## RFC
What do you guys think about this. I would just shorten the title and end it with ...

**Comment by jknnr** [comment]
I asked Daniel, Lena and myself, the result was – let it stay for now. It does not break the design concept and looks useful for the end user. If no one insists, we can freeze/close the issue

**Comment by maxvisser** [comment]
I will discuss this friday in sprint review to see what all stakeholders think about it.

**Comment by maxvisser** [comment]
I personally think the whole voucher should be clickable and should open the big QR-code slide up.

**Comment by GerbenBosschieter** [comment]
Is this even relevant anymore ? unassigned myself
