### ISSUE TITLE
change text on voucher details slide up 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#237]
## Context/goal: 

![z6slt8ni](https://user-images.githubusercontent.com/10818702/51477734-a657ae80-1d89-11e9-93d4-ffcd9b7cf83e.jpeg)

[ name of voucher ] 
Dit is uw voucher in de vorm van een QR-code.

For example:
Kindpakket
Dit is uw voucher in de vorm van een QR-code.

**Comment by maxvisser** [comment]
Also an issue on android

**Comment by ukakhmedoff** [comment]
done

**Comment by jknnr** [comment]
done
