### ISSUE TITLE
Keep voucher info in Me instead of redirecting to webshop.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#241]
## Description
The info about a voucher is really limited currently.
- Title of the voucher
- Name of organisation who distributed the voucher
- The amount of the budget

If the user wants more information about the voucher he can press "voucher info", the user will be redirected to the webshop of the webshop.

## Problem
When the user presses the button go to to the voucher info, he has to log in on the webshop while he is already logged in on the me-app. The user flow doesn't feels a little bit awkward. And I don't see a reason why we cant show this information with the app it self.

## Enhancement
What about a new page for in the me-app with the following user flow:
1. User goes to voucher
2. User presses voucher info
3. User gets a new page with the following information about the voucher.
- Title of the voucher
- Name of organisation who distributed the voucher
- The amount of the budget
- Expire date
- Contact information of organisation who distributed the voucher
- Information about the usage of the voucher (so the same info if someone presses the voucher itself)

## Additional info
Before implementing, lets have a discussion. Or upvote if you just agree :)

**Comment by maxvisser** [comment]
Hi Gerben; I think I will first do an MVP of this with login on webshop (using new short token authentication).

**Comment by maxvisser** [comment]
This is MVP is implemented will close this issue.
