### ISSUE TITLE
Change notification after payment confirmation.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#242]
## Context/goal: 
After the provider scans a QR-Code and confirms the payment he will be notified with a confirmation message.

**Android**: Betaling geslaagd
**iOS**:  Title: Succes, Description: Betaling geslaagd.

Lets change this to inform the provider even more.

**Android**: Betaling geslaagd! De verwerking van de betaling kan maximaal 3 werkdagen duren.
**iOS**:  **Title:** Succes, Description: Betaling geslaagd! De verwerking van de betaling kan maximaal 3 werkdagen duren.
English for both platforms:
Payment succeeded! The processing can take up to 3 business days.

**Comment by jknnr** [comment]
Currently can not do that, need Valentin

**Comment by maxvisser** [comment]
This is just a cosmetic change

**Comment by jknnr** [comment]
ah yes, sorry, will do

**Comment by jknnr** [comment]
fixed
