### ISSUE TITLE
Delete the crash button when building the demo build

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#243]
## Context/goal: 
The **press to crash** button is a great functionality to test Crashlytics feedback.
It's currently added to every build expect if production is build.

We are going to use the demo build more often now for presenting it to potential stakeholders. @danieltcacenco can you delete the **press to crash**  button if Demo is build? It looks a bit sloppy if we're going to use it in presentations.

**Comment by jknnr** [comment]
done
