### ISSUE TITLE
Provider information set to private results in a error

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#244]
## Prerequisites

1. create an organisation
2. create a product
3. buy product as citizen

## Description

Me on android has a bug where the list of voucher does not get loaded if a provider has set his data to private (not public). The data is shared when you bought the product but I think we use the wrong API route in the list.

## Steps to Reproduce (bug report)

1. use me android any version
2. login as an identity that has a product voucher
3. product voucher's provider should have his information set to private

**Expected behavior:** loads information of provider, the information is available on a different api route

**Actual behavior:** list does not get loaded, gives error.

**Reproduces how often:** 100% of the time

**Comment by jknnr** [comment]
fixed
