### ISSUE TITLE
Being logged out when you denied camera permissions

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#245]
## Context/goal: 
this needs to be checked on both iOS and Android

**Comment by jknnr** [comment]
@maxvisser could you check this one if it reappears?

**Comment by jknnr** [comment]
can not reproduce this still, tried on 2 devices.

**Comment by maxvisser** [comment]
checked again and it happens 100% of the time on my device

**Comment by maxvisser** [comment]
You deny permissions and it logs you out

**Comment by jknnr** [comment]
@maxvisser you can show me on monday on your device. Or give the exact steps or screen recording:)

**Comment by jknnr** [comment]
fixed
