### ISSUE TITLE
Me app logs me out when I have QR-code scanner open for a long time

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#246]
## Context/goal: 
I have the me app open for atleast 5 min on the scanner, I tried to scan to login again because the webshop logged me out after 15 min. The app gives 'unexpected error', when I go back, I get logged out in me-app

**Comment by jknnr** [comment]
Can't reproduce, need to have a call

**Comment by maxvisser** [comment]
If you send me  APK I can try to reproduce it

**Comment by maxvisser** [comment]
This happened again to a user but we are not sure why. Needs probably extensive testing to refine this issue

**Comment by jamalv** [comment]
I also heard some signals about users getting logged out. Some ideas: maybe it has to do with the memory? As in; something is stored there, but as the memory gets full / cleared up / it causes this logout? Ways to test this? Get some android app that clears the memory > open me and log in > put the app in the background > clear the memory > are you still logged in? 

also: open me and log in > clear memory using app or other method > restart device > still logged in?
