### ISSUE TITLE
'Sorry not enough funds on voucher' needs translation

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#253]
I get this message when I fill in 0,01 as an amount.

'Er staat niet genoeg geld op de voucher'

**Comment by danieltcacenco** [comment]
This error coming from server.

**Comment by jknnr** [comment]
Assigned @dev-rminds, Valentin will have a look

**Comment by danieltcacenco** [comment]
done

**Comment by jknnr** [comment]
422 code of error
en: Sorry not enough funds on voucher
nl: Er staat niet genoeg geld op de voucher

**Comment by maxvisser** [comment]
I'm confused about this issue. If this is a error because of status code 422 lets change the text... Does not make sense right?

EN 'Transaction amount too low.'
NL 'Transactiebedrag te laag.'

**Comment by maxvisser** [comment]
0,10 is 10 cent
0,01 is 1 cent
0,001 should give an error
