### ISSUE TITLE
Implement "No internet" error.

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#259]
## Context/goal: 
Currently it gives the wrong error. "You are not allowed to scan this voucher or it was already used."

## Task
Implement handling no internet connection on all related pages. Especially on doing a transaction.
suggestions: show always a red bar at the top when no stable internet connection is currently the case.

- [ ]  implement better error handling on internet connection
- [ ] implement better status showing to user that he needs to connect to internet.

**Comment by SjoerdHilhorst** [comment]
Example from IOS how it should be implemented.

![image](https://user-images.githubusercontent.com/48722300/73163281-f0d3df80-40ef-11ea-88cb-c4f89a717eb9.png)
