### ISSUE TITLE
Move logout button on set passcode screen

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#260]
## Context/goal: 
The logout button does not fit on the small screen of Nokia 1, so I think we need to redesign this screen a little bit by placing the logout button from the left from 0, or put this function in the menu in the top right. Also a dialog window should be added on this button, smth like: "Are you sure you want to log out?"

**Comment by maxvisser** [comment]
could you make a screenshot?

**Comment by jknnr** [comment]
It was partially fixed. But still there is no logout button visible cause its under the 0, so not visible on small screens. I will update the task. Currently it looks good, but the problem of forgetting your passcode reappears if there is no "log out" button.

**Comment by maxvisser** [comment]
@GerbenBosschieter could you look where logout button on ios is located. maybe can also enhance android the same way.

**Comment by jamalv** [comment]
Is this still relevant?
