### ISSUE TITLE
The picture on the voucher overlays the text when its long

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#265]
Happens for example on smaller screens; photo is from Nokia 1
![img_8946](https://user-images.githubusercontent.com/32199937/53729706-29365380-3e76-11e9-9766-812a69af2573.JPG)

## Task
- [ ] trim long names to a maximum of one row on the list.

**Comment by maxvisser** [comment]
Saw this aswell. like the ancient screenshot

**Comment by SjoerdHilhorst** [comment]
Example of how it should be implemented
 from IOS
![image](https://user-images.githubusercontent.com/48722300/73163035-64c1b800-40ef-11ea-8b75-493407260f01.png)

**Comment by maxvisser** [comment]
is fixed
