### ISSUE TITLE
wrong translation 'Ander apparaat toevoegen'

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#268]
## Context/goal: 
Should be 'Via ander apparaat inloggen'

**Comment by jknnr** [comment]
Via ander apparaat inloggen will not fit into the button. We can only add 1 more symbol.

**Comment by maxvisser** [comment]
'Login via ander apparaat' is three symbols less

**Comment by danieltcacenco** [comment]
Can you put some screen where is that, please.

**Comment by maxvisser** [comment]
button is on page 'Ik heb al een profiel'  / ' I already have a identity'

**Comment by danieltcacenco** [comment]
done
