### ISSUE TITLE
The app crashes on "Fill in passcode screen."

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#269]
**Expected behavior:** Log in after fill the passcode

**Actual behavior:** I set up the password, get out of the app. Open it again. Enter the wrong passcode. There is an X in the top right corner. When I tap it multiple times the app crashes. Thats it.

**Reproduces how often:** 100%

We need to remove the X at all, there is no reason why it's there now

**Comment by maxvisser** [comment]
As in, not critical, we still need to move the log out button aswell

**Comment by jknnr** [comment]
> I can not reproduce it. I get logged out instead of crashing. Seems ok

yes, but on Nokia 1 it happens all the time

**Comment by jknnr** [comment]
I will update the issue, its not that easy as I thought:)

**Comment by maxvisser** [comment]
I reproduced it by pressing x multiple times when filling in wrong pascode on 0.0.7 currently in playstore
