### ISSUE TITLE
Add enable/disable flashlight on QR-code scanner screen

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#277]
## Context/goal: 

DoD
- Add symbol to top right corner of QR-code scanner
- When flashlight is on, show symbol
- When flashlight is off, show outline of symbol

You can chose the symbol: a flashlight, a lightning strike or any other icon that can resemble the flashlight

**Comment by maxvisser** [comment]
Can be a bit smaller

and maybe later look for a better icon

**Comment by GerbenBosschieter** [comment]
- Add symbol to top right corner of QR-code scanner -> done
- When flashlight is on, show symbol -> done
- When flashlight is off, show outline of symbol - kind of done

The icon does change if you turn on/off the flashlight. The power button is on top when the flashlight is on and the power button is on the bottom if it's turned of (i like this detail). And the color of the icon is changing when switching

**Comment by maxvisser** [comment]
Done
