### ISSUE TITLE
Help screen on QR-code scanner

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#278]
## Context/goal: 
Add help screen on QR-code scanner. This will add some text above and below the blue square.

Title: NL "Scan een code om in te loggen of start een betaling!" EN "Scan a code to login or to start a payment."
Subtitle: NL "Met de Me Scanner kun je inloggen of betalingen verrichten zodra je een QR-code scant." EN "You can login with the Me Scanner and do payments when you scan a QR-code."

Below square:
EN: "Een QR-code kom je tegen als een klant wilt betalen of wanneer je wilt inloggen op een gebruikersomgeving." NL: "You find a QR-code when a customer wants to pay or when you want to login on a user environment. "

Add a button on footer 
Button: NL: "Terug naar scanner" EN: "Back to scanner"

**Comment by danieltcacenco** [comment]
We need some design for that?

**Comment by jamalv** [comment]
With the training that is included in the signup flow (scanning 2 qr codes) I think this issue is redundant
