### ISSUE TITLE
Show expiration date on voucher details

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#281]
## Context/goal: 

For a user this is pretty important information, it is the date that the voucher can not be used anymore and the fund are getting locked.

We currently don't show this date in the app.
Best place to show it right away is when you press the QR-code and make it bigger in a popup.

DoD
- [ ] Add below "Dit is uw voucher in de vorm van een QR-code':

EN: "This voucher expires on 1st of January 2020"
NL: "Gebruik deze voucher voor 1 Januari 2020"

**Comment by GerbenBosschieter** [comment]
It says: Dit je is persoonlijke QR-code.
@danieltcacenco could you change this sentence to: **Dit is uw voucher in de vorm van een QR-code**

**Comment by maxvisser** [comment]
still not fixed
