### ISSUE TITLE
Proposal: Having only one QR-code, a hot wallet

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#283]
## Context/goal: 
We already got some more insight on how the system is used with a 1000 users. Some users bought a product voucher. They showed (instead of the productvoucher) their budget voucher QR-code to provider, this resulted in a lot of confusing for both parties. 

As we grow, a implementation will have multiple funds, products and therefore alot of QR-codes. This will get more complicated for the user overtime, 

Going forward we need to rethink how the payment system works, I propose to switch to a 'hot wallet' system where the user can create hot wallets himself. When the user creates his account he will have one hot wallet. (he can create more up to 5).

He can assign a hot wallet to a product or budget voucher. The user can unassign the hot wallet when he loses the QR-code, adding security to the paper wallets aswell. 

In the Me-app you will not show any budget or product voucher QR-codes anymore. (or the new hot wallet). Instead the  provider will have a QR-code. He can print out his QR-code and show this QR-code to the user. (or show it via Me-app). Citizen will scan this QR-code instead of showing his own QR-code  to the shopkeeper. Citizen will create a transaction by filling in his/her pincode. 

When provider uses his Me-app to show a QR-code he will click on 'Request' like in BUNQ, fill in the amount, this creates a QR-code that the citizen will scan. 

If printed out, the user can send a product vouchers to the provider. On budget level the provider needs to accept the payment.

**Comment by maxvisser** [comment]
@jamalv we talked about this shortly this afternoon, I really liked the idea of changing the payment system to a system link BUNQ. Can you help me refine this issue?

**Comment by jamalv** [comment]
Great issue, I think the goal of having only one QR code is a very good one. As this influences the core interaction this needs some good thinking. We can take it along in our refinement session.

**Comment by GerbenBosschieter** [comment]
I like the concept, but it is really something different than how we use it on our current use case.
I would like it more to think about a short term solutions that fits the use cases and is scalable.  The idea you propose is so different that it will probably cause comparable issues that you address.

**Comment by maxvisser** [comment]
The part of changing the Me-app can only be implemented after we implement the valuta functionality https://github.com/teamforus/forus/issues/671
This epic will implement a wallet functionality what enables sending and receiving euro's. This will take alot of research and development

The hot wallet part can already be implemented on the short term;
