### ISSUE TITLE
Transaction: Show product voucher when scanning budget voucher

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#284]
# Users are confused with different QR-codes. 
Current user flow:
1. User activates budget voucher
2. User buys product voucher on webshop for 150 euro - > budget voucher is becoming 0.0 euro's.
3. User is confused about the QR-codes and shows the budget voucher instead of product voucher.
4. Providers scans the QR-code, error is displayed that budget is to low.
5. Frustrated user goes back to home without product.

Desired user flow:
1. User activates budget voucher
2. User buys product voucher on webshop for 150 euro - > budget voucher is becoming 0.0 euro's.
3. User is confused about the QR-codes and shows the budget voucher instead of product voucher.
4. Providers scans the QR-code.
5. New screen is displayed with the reserved product vouchers. The provider can select one of these product vouchers to finish the transactions. 
6. User happy with a product.

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/61362640-d1c3dd80-a882-11e9-8f1a-05a44153e967.png)

**Comment by maxvisser** [comment]
This can be implemented after fixing https://github.com/teamforus/forus/issues/955

**Comment by maxvisser** [comment]
still needs to be fixed on android

**Comment by maxvisser** [comment]
on android after doing transaction user returns to reserve product voucher list; user should return to scanner instead.

**Comment by maxvisser** [comment]
This also stopped working on latest build of iOS 

![image](https://user-images.githubusercontent.com/10818702/75434139-66caa100-5951-11ea-9366-2b5193a09f9a.png)

scanning this voucher with provider_ww@asdasd.nl does not work
