### ISSUE TITLE
Push notifications: No content or text after push notification

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#285]
# Description:

I am getting questions of providers that they don't know what to do with the push notifications.
There are confused and something went wrong.

On iOS it only shows the push notification itself with the following content:
- Me
- Title of the message

If they open the notification they get redirected to the app without any explanation.
If they swipe to the left to get the option: See more, no message is shown.

So in this current situation it only causes confusion and useless support questions.

## Solution:
I am not sure where this problem occurs , but last time I talked about it with @danieltcacenco it was somewhere on the backend.
Fix the issue with the message or remove push notifications for iOS.

**Comment by maxvisser** [comment]
can we somehow test it @danieltcacenco could you add a screenshot of here of it working?

**Comment by GerbenBosschieter** [comment]
Fixed, thanks to @pantyukhov !
