### ISSUE TITLE
Make whole camera area active when scanning qr code

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#286]
right now you need to place the qr code in the square area. it is better to have the whole camera area be active, it feels more intuitive and responsive.

**Comment by danieltcacenco** [comment]
it mean to delete those square or maybe just to put on whole area?

**Comment by jamalv** [comment]
how it looks can stay the same. 

I just mean that it scans the whole image instead of only the square area, so that it will also scan this:

![ctxC2igC](https://user-images.githubusercontent.com/30194799/56650247-e713dc00-6686-11e9-9d52-ac7af81f590b.jpeg)
