### ISSUE TITLE
Moving iOS-app structure to MVVM

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#288]
Talked with @danieltcacenco about this in latest session; Restructering the app to be more robuust.

**Comment by jamalv** [comment]
It is already MVC, Daniel proposed MVVM, I believe :)

**Comment by maxvisser** [comment]
made https://github.com/teamforus/res-me-ios for this purpose

**Comment by jamalv** [comment]
why does it need a new repository? could it not just be a research/mvvm branch?

**Comment by maxvisser** [comment]
He wants to start from scratch

**Comment by jamalv** [comment]
I don't think that really matters? He could create the branch, delete everything, do a commit and then start from scratch?

**Comment by maxvisser** [comment]
model view view-modal
