### ISSUE TITLE
Cannot clone this repository using GitHub desktop

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#29]
Getting the following error:
<img width="603" alt="screen shot 2018-05-03 at 13 03 13" src="https://user-images.githubusercontent.com/30194799/39573696-8283a222-4ed4-11e8-85a7-0ca465f05479.png">

**Comment by maxvisser** [comment]
![gitdesktop](https://user-images.githubusercontent.com/10818702/39574616-27fbc592-4ed8-11e8-9fba-612c9d3c008f.png)
Get the same error on windows

**Comment by maxvisser** [comment]
Jamal can you check if this is still an issue for you?

**Comment by jamalv** [comment]
has been fixed since we cleaned the branch
