### ISSUE TITLE
hide add new record

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#296]
## Context/goal: 
hide add new records 

function should be toggle on the right environment (beta or demo)

**Comment by GerbenBosschieter** [comment]
Cant test this, I have to re invite my apple Id to get acces to the beta app (beta and demo are same btw).  And with the invitation I already had It also tells me I cant do anything.
![Screen Shot 2019-07-09 at 15 00 56](https://user-images.githubusercontent.com/38419514/60889909-6793b300-a25a-11e9-9d82-9edf931a288b.png)

**Comment by GerbenBosschieter** [comment]
tested, done
