### ISSUE TITLE
Add expire label on voucher

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#297]
## Context/goal: 
Currently we show expired vouchers in Me, lets hide expired vouchers

A check on list is needed to only display voucher that has an expire_date >= today

**Comment by jamalv** [comment]
I wouldn’t like to hide them completely. For informational purposes it would be nice for the user to still see their old transactions. I would prefer to hide the qr code, and show an expired message instead.

Next to that, an option to manually archive vouchers could also be nice. 

Example: swipe right / left on voucher, show archive option. Then add an “view archived” button on the bottom of the list. For example how bunq does it:

![CCE48DA4-5104-4B7D-B519-915D6FACEA23](https://user-images.githubusercontent.com/30194799/60488069-469ef100-9ca1-11e9-940d-326bf3e5140f.jpeg)

**Comment by maxvisser** [comment]
Yes discussed this with Daniel aswell but designs are needed for this

**Comment by maxvisser** [comment]
Option now is to show them all and label or don't show them

**Comment by GerbenBosschieter** [comment]
I've tested this. No label, and the voucher doesn't disappear.  The voucher details does tell me the correct end date. I've asked @danieltcacenco and het told me that this is how it should be.

**Comment by maxvisser** [comment]
voucher x 01/01/2019 till 31/12/2019 <-- voucher should be displayed in list
voucher x 01/01/2019 till 31/06/2019 <-- voucher should not be displayed at all

current date 01/07/2019

**Comment by maxvisser** [comment]
in discussion with daniel we decided to add a label instead.

'Expired' -> 'Verlopen'
