### ISSUE TITLE
Designs feedback: contextual messages

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#30]
My main point of feedback on the designs is that I think a lot of the screens can be more contextual. 

I made a screen recording give an idea how it works: [contextual alert views (customizable).zip](https://github.com/teamforus/me/files/1976441/contextual.alert.views.customizable.zip)

It is from this framework (iOS): https://github.com/SwiftKickMobile/SwiftMessages all the views seem to be easily customisable.

I marked/updated the screenshots that I think this applies to, I tried to export it but somehow it leaves out a bunch of stuff so for now this is [the direct draw.io link](https://drive.google.com/file/d/14DzXdb4HcLhX9im36pNMC7xWE_BoXLIz/view?usp=sharing)

**Comment by danrminds** [comment]
Still valid? @jamalv

**Comment by maxvisser** [comment]
I watched the video in the .zip archive; What I like about is that the notifications are on top and decisions/inputs are on the bottom; I think conceptionally this is a great approach; when you use a smartphone with one hand; you want to put as much of the buttons on the bottom part of the screen, so you can reach it with your thumb.

From jamal's video:
<img src="https://user-images.githubusercontent.com/10818702/40782743-9b689960-64e0-11e8-96ab-f9d7466c53b9.png" height=100>

Me app popup
<img src="https://user-images.githubusercontent.com/10818702/40782745-9cc98c38-64e0-11e8-9ec0-1d9712798147.png" height=100>

I think we should move them down.

**Comment by maxvisser** [comment]
@jamalv do you still think this is relevant?

**Comment by maxvisser** [comment]
I think with the current progress, this is solved.
