### ISSUE TITLE
Can't create New Me - Profile

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#302]
## Prerequisites

1. Email adres without Me-profile
2. Me-app
3. Device with small screen (I assume)

## Description
I've tried to create a new profile on the Me - app. But this doesn't seem to work The screens of the Me app are stuck and are not getting to the next screen (verify your e-mailadres)
I've tried to do this a couple times, there was only one moment i got the **Verify your e-mail screen**.
After that (and yes I closed the app a couple times) there was no moment that I could go to the next screen. I did get an e-mail from the notification server, so the button to create the profile works, but doesn't redirect me to the next screen.

- On smaller screens the button to go back is impossible to press it doesn/t go back or the button simply doesn't work. Not sure how this is now with bigger screen
- Change text from : IK HEB AL EEN ME IDENTITEIT to IK HEB AL EEN PROFIEL

## Steps to Reproduce (bug report)

1. Open me (the res-me-ios)
2. Create new profile
3. Enter data (email, name, lastname)
4. Press Add profile -> if you do get redirected to the verify e-mail page, try to use the return button to see if that works. 
5. If you got the verify email page from step 4, close app and try again to see if you get the bug.

**Expected behavior:** [What you expect to happen]
- Receive e-mail to verify
- Get redirected To verify e-mail page

**Actual behavior:** [What actually happens]
- Receive e-mail to verify
- No redirection to veirfy email page

**Reproduces how often:** [What percentage of the time does it reproduce?]
90%, if the bug is there it will not disappear. Not even if you close the

**Comment by danieltcacenco** [comment]
We should think about that because now email i got after 10 minutes and in this case already i can't use those email, but when i try to create new profile with the same email i got a message like "this email already is taken".

**Comment by maxvisser** [comment]
Did you try to reproduce the issue, what did you find? Its about not showing the e-mail activation screen;

please use https://temp-mail.org for testing with temporary e-mail adresses
