### ISSUE TITLE
Localisation: Close needs to be translated

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#306]
## Context/goal: 
![NOZgaX0q](https://user-images.githubusercontent.com/10818702/61052065-e7508780-a3ea-11e9-8f01-1c2594155d30.jpeg)

Close button in left top corner needs to be localised to 'Sluit'

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
Still not fixed in build 8
![E71lxKwU](https://user-images.githubusercontent.com/10818702/61119367-f4c54a80-a49a-11e9-9b9d-87fb440a649d.jpeg)

**Comment by danieltcacenco** [comment]
done
