### ISSUE TITLE
Remove blue avatar to open up records on voucher page.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#307]
## Context/goal: 
![mG7E8WxT](https://user-images.githubusercontent.com/10818702/61052195-2f6faa00-a3eb-11e9-9f71-86f3a8ff9bff.jpeg)

Remove this blue avatar icon on voucher page:
![image](https://user-images.githubusercontent.com/10818702/61052213-3a2a3f00-a3eb-11e9-9b0b-9a64a28d1a97.png)

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
This is still an issue in build 8

**Comment by danieltcacenco** [comment]
done
