### ISSUE TITLE
Textual change: Dit is uw voucher in de vorm van een QR-code

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#308]
## Context/goal: 
![xFOqUcam](https://user-images.githubusercontent.com/10818702/61052540-ecfa9d00-a3eb-11e9-8b7e-8d85547e3584.jpeg)

It says: Dit je is persoonlijke QR-code.
@danieltcacenco could you change this sentence to: Dit is uw voucher in de vorm van een QR-code

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
![p2bC1TNj](https://user-images.githubusercontent.com/10818702/61119757-d27ffc80-a49b-11e9-9b71-cfbe6d474ac6.jpeg)

On small screen the whole sentence is short, while there is enough room

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
@gerbenbosschieter can you test this on you iphone 6s

**Comment by maxvisser** [comment]
@danieltcacenco text is still wrong on productvoucher in build 13

**Comment by maxvisser** [comment]
Still in build 16
