### ISSUE TITLE
Localisation: Yes/No when scan to login

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#309]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/61052731-44007200-a3ec-11e9-8528-447b0b7264dc.png)

When you confirm you want to login
@danieltcacenco the option to choose are Yes and No, could you change this to dutch Ja and Nee and can you change the text to: "Weet je zeker dat je op deze website of dit apparaat wilt inloggen ?"

## tasks:

- [ ] 'Yes' -> 'Ja'
- [ ] 'No' -> 'Nee'

**Comment by danieltcacenco** [comment]
done
