### ISSUE TITLE
Material design vs iOS design

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#31]
## Sort of Issue

Organizational task

## Description

There are currently two design options. I propose to adjust the design to native android, material design for the android me app. @martijndoornik has made alot of progress on implementing the me app screens in material design.

we could decide if we want to make changes to this approach and maybe step away from some elements of material design. 

Goal: make the iOS app and android app a uniform user experience. A android user and a iOS user that are friends should not have conflicted user experiences. Also giving support for two different user interfaces is harder. 

## Additional Information (optional)

Material design:
https://material.io/

Implemented designs on Android:

| scanner | records | wallet | token detail | send | ask | options |
|---------|---------|--------|--------------|------|-----|---------|
<img src="https://github.com/teamforus/me/blob/master/docs/android-v0.1/scanner.jpg?raw=true" height="100" />|<img src="https://github.com/teamforus/me/blob/master/docs/android-v0.1/records-dutch.jpg?raw=true" height="100" />|<img src="https://github.com/teamforus/me/blob/master/docs/android-v0.1/eigendom.jpg?raw=true" height="100" /> |<img src="https://github.com/teamforus/me/blob/master/docs/android-v0.1/token-detail.jpg?raw=true" height="100" />|<img src="https://github.com/teamforus/me/blob/master/docs/android-v0.1/send.jpg?raw=true" height="100" />|<img src="https://github.com/teamforus/me/blob/master/docs/android-v0.1/ask.jpg?raw=true" height="100" />|<img src="https://github.com/teamforus/me/blob/master/docs/android-v0.1/extra-options.jpg?raw=true" height="100" />

**Comment by maxvisser** [comment]
![](https://lh3.googleusercontent.com/ziC_EYhCTmLaBC-NfLkf_3hPc9zM4mXjyAkOJ0Xn9_kVxSG8gNbmXNg3N67XRj9iHWHJfujfAZpvvoQ6fvJdsKiHdqtK8NE_ZuORIs47HtdaUM4cNq25a3BMQl990GE0jFtRTl0TlmttZb9p9RoUsmtQsIkEOCj1xtJSp6jHQ3G6rcrSEuiloBWQ5iWus-JKR0jx0PYCRDxsoUQo1WrXVMKLTP2y3-Ja37JKRdwxTF_67Ul0yEw7DPVMOx5dc1M22vpD7jBqAxOy4_EL5EkowB5X85CGm_zPNM88JAVa-9ZhGmpyfuc9y2qWJ9K62cyGtdceHBY67hmlXafZoRVh0ezAM_VRxeKCZY3dpIRqahnSR8Tl1d-z5mJXNDouZMRpy6JwZK9OMolyJMcerMfQZfq68TqLog5DGiX5TTXSs3V99dhx7cQjFeyWwghWj0qZiKmgayrshi6y8EPe2XpUkN8CRDulhRK9G8Nnj2ovJwSjU6XFGTH8UlqY_1ZJXUCL1HoogHbBKFmL5LkbXCiWTNozRKTGIc5AyLRlYLsBnQQ4rkjsQkYKRf14DiAMtqF2rWCsq5KRlB0HcHEK_r_-dDrGITAMk9SDkDs4Oyrk=w450-h900-no)

**Comment by jamalv** [comment]
One of the main advantages of going native is to give a user an experience that is "native" to the platform. Therefore I think it is okay if are design differences between iOS and Android, as long as the functionality is equal. 

The challenge of the developer should be to implement the designs as closely as possible. If there are disagreements about the design, it should be coordinated with the designer and the designs should be updated, instead of the developer breaking the design, this might lead to suboptimal results.

**Comment by maxvisser** [comment]
I think there are alot of small differences between the designs and the current implementation. We should maybe plan a meeting to discus the differences and decide what we still implement and do next on the front-end.

**Comment by maxvisser** [comment]
Contemplated with Martijn and Dan about the issues with the current designs for Android. Most of them come back to gradients. Even the icons have gradients, but the standard material design icons are really ugly. Maybe we can change the icons for the categories to flat design and only 3 colors for android?

**Comment by danrminds** [comment]
Discussed with Martijn about the compliance of the designs with android and material design practices. 

There are some aspects that will need adjustments (will work on them). 
In rest - most of the practices are matched. Will update this issue during development process

**Comment by maxvisser** [comment]
I think this issue is being solved, I will close it for now until it is relevant again.
