### ISSUE TITLE
Textual change: subtitle of bevestig code

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#313]
## Context/goal: 
![jZULpxzA](https://user-images.githubusercontent.com/10818702/61053928-c68a3100-a3ee-11e9-960f-ce9456e25d22.jpeg)

When creating a passcode for login, on second screen you want to confirm your passcode the subtitle is wrong in dutch localisation.

'Voer een nieuwe inlogcode in' should be 'Bevestig de inlogcode door hem nogmaals in te voeren.'

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
You use same subtitle for both screens. First screen should have a different subtitle.

**Comment by maxvisser** [comment]
## Creating passcode

NL Title: Inlogcode instellen
subtitle: Stel een inlogcode in van vier cijfers.
Screen:
![v6q9OKTn](https://user-images.githubusercontent.com/10818702/61119197-98622b00-a49a-11e9-9822-b3f5a94e3e10.jpeg)

## Confirm passcode
NL: Bevestig inlogcode
Subtitle: Bevestig de inlogcode door hem nogmaals in te voeren.
![nqbBdaxL](https://user-images.githubusercontent.com/10818702/61119309-d2333180-a49a-11e9-96f5-d2a4d2c67b8f.jpeg)

**Comment by danieltcacenco** [comment]
done
