### ISSUE TITLE
Localisation: Success!

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#314]
## Context/goal: 
![1FQoNvOZ](https://user-images.githubusercontent.com/10818702/61054196-47492d00-a3ef-11e9-9784-a8fbcef9c866.jpeg)

'Success!' -> 'Succes!'

'De voucher is verzonden naar email' -> 'De voucher is verzonden naar uw e-mail.'

**Comment by danieltcacenco** [comment]
done
