### ISSUE TITLE
Textual change: 'Mail provider from product voucher'-popup

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#315]
## Context/goal: 
![1q7155ds](https://user-images.githubusercontent.com/10818702/61054568-fd147b80-a3ef-11e9-90ce-566b6d222f17.jpeg)

'E-Mail naar mij' -> 'Stuur een e-mail naar aanbieder'
'Vraag van Me-gebruiker' -> 'Bevestig om naar uw email-app te gaan om een bericht te sturen naar de aanbieder'

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
You use same popup for both instances:
E-mail naar mij button and clicking the e-mail of provider

This textual change should only be for clicking the e-mail of the provider

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
@danieltcacenco not fixed yet in build 10. You use now correctly a different label for each button but the text is switch around

E-mail naar mij should have the text :
title: E-Mail naarm ij
Description: Wilt u de voucher naar uw e-mail sturen

Pressing the provider e-mail adres should have the text:
Title: stuur een e-mail naar aanbieder
Description: Bevestig om naar uw e-mail app te gaan om een bericht te sturen naar de aanbieder.

**Comment by maxvisser** [comment]
Still not done in build 13

**Comment by maxvisser** [comment]
Comment of yesterday still not done in build 16

**Comment by maxvisser** [comment]
done
