### ISSUE TITLE
When no Given Name and Family Name center e-mailadres

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#316]
## Context/goal: 
![XUr4zqKA](https://user-images.githubusercontent.com/10818702/61055153-271a6d80-a3f1-11e9-9a96-ba6a4497ecf5.jpeg)

When a user does not have a Given Name or Family name the e-mail adres is off center

**Comment by danieltcacenco** [comment]
i think we shouldn't give a way to user create some profile without name

**Comment by maxvisser** [comment]
currently on webshop most of accounts are generated without first name, last name

**Comment by maxvisser** [comment]
So your solution is not applicable for current users, i think around 2500 users don't have their first and last name as a record

**Comment by danieltcacenco** [comment]
done
