### ISSUE TITLE
Make whole profile clickable to open up records page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#317]
## Context/goal: 
The two blue circles on profile page (me logo and profile icon) look pretty weird from design stand point

I propose to make the whole profile clickable and add a right sided arrow like this instead:
![image](https://user-images.githubusercontent.com/10818702/61057291-487d5880-a3f5-11e9-9088-6c310de7a02e.png)

**Comment by danieltcacenco** [comment]
done
