### ISSUE TITLE
Splitting vouchers (discussion)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#32]
## Sort of Issue

Enhancement

## Description

In decision week, I requested a feature to split vouchers for security reasons. In Kindpakket 1.1 a malicious shopkeeper can drain a whole voucher without an users consent. Therefore I proposed to let the user split a voucher in smaller amounts to make it more secure (don't take all your money to the shop, take only what you need). 

I now see that this feature is also in the Me app designs. This was not my intent with this feature. The Me app is secure. You have a pin and a large transaction can happen with consent. Splitting vouchers should only be a feature in the webshop. (old voucher needs to be deleted and a new voucher needs to be generated)

I also discussed this feature with Martijn. He sees alot of problems with migrating this feature to blockchain. We could also decide to put this feature on hold for the MVP and brainstorm on a better solution for security with paper wallets.

**Comment by jamalv** [comment]
Agreed that for the MVP of the app we can still leave this feature out. Since this is mostly is a "could have" and not a "must have" feature. For the webshop we can take it into consideration, but for the mvp I also don't think it is an essential feature.

**Comment by danrminds** [comment]
"(old voucher needs to be deleted and a new voucher needs to be generated)" -> actually only a transaction is generated for the old voucher, and a new voucher is generated

I agree that this feature can be left out in the MVP.

I also discussed with Martijn about the issue of complying to the ERC20 standard and the issue it can bring when migrating to blockchain. As we plan to have 2 API routes: api.forus.io and services.forus.io for things that can be decentralized and separate for which can not -> this feature can be kept in the part where functionality can not be decentralized.

**Comment by maxvisser** [comment]
This issue is resolved. For now we leave this feature out.
