### ISSUE TITLE
Translation file: record_types

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#325]
## Context/goal: 

key | type | EN | NL
-- | -- | -- | --
primary_email | string | Hoofd e-mail | Primary e-mail
email | string | Tweede e-mail | Secundary e-mail
given_name | string | Voornaam | Given name
family_name | string | Achternaam | 2018-11-22 15:12:45
children | string | Kinderen | Children
children_nth | number | Aantal kinderen | Amount of children
parent | string | Ouder | Parent
address | string | Adres | Address
birth_date | string | Geboortedatum | Date of birth
gender | string | Geslacht | Gender
spouse | string | Partner | Spouse
etax_id | string | BTW-nummer | Tax ID
telephone | string | Telefoonnummer | Telephonenumber
net_worth | number | Vermogen | Net worth
base_salary | number | Salaris | Salary
bsn | number | Burgerservicenummer | BSN
kindpakket_2018_eligible | string | Recht op Kindpakket 2018 | Eligible for Kindpakket 2018
meedoenregeling_2018_eligible | string | Recht op Meedoenregeling 2018 | Eligible for Meedoenregeling 2018
klantnummer  | number | Klantnummer | Customernumber

**Comment by maxvisser** [comment]
Hmm. @danieltcacenco I just tested this. All works as intended but on some environment we have diferent _eligible keys. I think storing these keys which are highly adjusted on device is a bad idea.. 

I asked  @dev-rminds for a solution; 

after this commit you can use NL/EN locale in request header to get back the right language.
https://github.com/teamforus/forus-backend/commit/baae7f97682da1191f39eaa5d93acfe1a82953c8

**Comment by danieltcacenco** [comment]
ok, only i need key of header.

**Comment by danieltcacenco** [comment]
/records 

i still get in such form

**Comment by maxvisser** [comment]
on /identity/record-types it should work
![image](https://user-images.githubusercontent.com/10818702/61620522-4460fe80-ac71-11e9-9ac3-685b48db7d1f.png)
