### ISSUE TITLE
new Error messages from backend

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#328]
## Context/goal: 

        'expired' => 'De voucher is verlopen.',
        'product_voucher_used' => 'De voucher voor deze aanbieding is al gebruikt!',
        'provider_not_applied' => 'U mag deze voucher niet scannen! Uw organisatie is nog niet aangemeld bij het fonds van deze voucher.',
        'provider_pending' => 'U mag deze voucher niet scannen! Status voor aanmelding van het fonds van deze voucher is wachtend.',
        'provider_denied' => 'U mag deze voucher niet scannen! Uw organisatie is geweigerd om deel te nemen aan het fonds. Zoek contact op met sponsor voor een reden.',
        'fund_not_active' => 'U mag deze voucher nog niet scannen! Het fonds is niet actief.',
        'not_enough_funds' => 'Onvoldoende tegoed op de voucher.'

would be nice to get these error messages directly from backend

**Comment by maxvisser** [comment]
Did you implement this @danieltcacenco; the backend gives back more precise errors on scanning vouchers

**Comment by danieltcacenco** [comment]
done
