### ISSUE TITLE
Wireframe full app

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#329]
## Context/goal: 
For the design cycle it is very useful to have wireframes that are in sync with the status of the current master branch of the app. This issue is about creating those wireframes and adding them to this repository.

Related Forus issue: https://github.com/teamforus/forus/issues/974

**Comment by maxvisser** [comment]
Hi in this repository on the develop branch I already made some wireframes in the design folder

**Comment by jamalv** [comment]
I created wireframes for the current version in: https://github.com/teamforus/me/tree/wireframes/wireframes

And renamed your wireframes draft-me.html
