### ISSUE TITLE
Making multiple payment request when pressing

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#332]
## Context/goal: 
I found a problem with the transaction submit button; when pressed multiple times a user can accidently do multiple transactions.

![kNpQGnaa](https://user-images.githubusercontent.com/10818702/64160087-9a61be00-ce3b-11e9-8054-4b04de39a6cd.jpeg)

![image](https://user-images.githubusercontent.com/10818702/64160462-42778700-ce3c-11e9-9023-8ffa0c3c7f2b.png)

## tasks
- [ ] reproduce issue
- [ ] fix issue

**Comment by danieltcacenco** [comment]
done
