### ISSUE TITLE
No error when e-mail adres is used on creating identity

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#333]
## Context/goal: 
When creating an identity; there is no error when e-mail is already used.

**Comment by maxvisser** [comment]
would be nice to add a popup if email is already used;
English title: Do you want to login instead?
English description: Your e-mail address is already used, do you instead want to login using this e-mail address?

Dutch title: E-mailadres ingebruik! Wilt u inloggen?
Dutch description: Dit e-mail adres is al gebruikt. Wilt u inloggen met dit e-mailadres?

If user presses ' Confirm ' / ' Bevestig '. we will send a login mail to e-mail address filled in.

**Comment by danieltcacenco** [comment]
done
