### ISSUE TITLE
Epic. Signup-flow. Requester - Scanning a validation request QR

### ISSUE THREAD

**Issue by danrminds** [teamforus/me#341]
## Context/goal: 
![Screenshot 2019-10-07 16 50 57](https://user-images.githubusercontent.com/33207036/66322911-2d9e7f80-e923-11e9-8e1a-8c0fbc915dfd.png)

After scanning this QR - you should get a validation modal to choose what organisation you want to validate for. 

It should display the Organisation name, logo
Design it for 3 options:

1. Gemeente Zuidhorn
2. Stichting Leergeld
3. Global validation (not assigned to an organisation) - needs an alternative here instead of the logo, maybe also a bit different color schema, etc.

**Comment by Myshelova** [comment]
iOS: https://zpl.io/bLGxKJ6
Android: https://zpl.io/2p7lnNl
