### ISSUE TITLE
Provider signup. Test transaction implementation

### ISSUE THREAD

**Issue by danrminds** [teamforus/me#343]
## Context/goal: 
Easiest to implement it is with a new "qrcode_type" in the QRcode itself. When the app will scan this qrcode and sees the new type - will perform different actions than usually, by simulating a transaction.

Testable with https://dev.forus.io/provider/#!/sign-up

BaseURL: dev.api.forus.io

The simulation (after scanning the QR-code) - should display:

1. The screen to fill in an amount of the transaction
2. Go through the normal workflow / screens of making a transaction, but not making an actual transaction in fact. It will just simulate until it will show a success message.

**Comment by danieltcacenco** [comment]
done
