### ISSUE TITLE
me-ios: add new webshop in about me

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#352]
- de Winterswijk webshop;
- de Oost Gelre webshop;
- de Berkelland webshop;
- de Noordoostpolder webshop
- de Kerstpakket webshop;

|Property | Value|
|------------ | -------------|
| Bundle ID | io.forus.me.test (49) |
| Device | iPhone XR |
| Operating System | iOS 12.0 |
| Screen size | 6.1 in - 2.56 x 5.54 in |
| Viewport | 414 x 896 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/e5d30e7ec2de3000acdce14403f72168d890e5a2/realios_iPhone_XR.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/e5d30e7ec2de3000acdce14403f72168d890e5a2/realios_iPhone_XR.jpg)

[Log URL](https://api.browserstack.com/applive/sessions/f3c2566a35f125ba57b5f97cf593e073e05e6652/devicelogs)

**Comment by maxvisser** [comment]
Hi daniel! I see you overwritten the old webshops; these should stay in the list.
full list:

- de Westerkwartier webshop;
- de Nijmegen webshop;
- de Winterswijk webshop;
- de Oost Gelre webshop;
- de Berkelland webshop;
- de Noordoostpolder webshop
- de Kerstpakket webshop;

**Comment by jamalv** [comment]
done
