### ISSUE TITLE
Me-ios: send error reports should be less intrusive

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#354]
## Task: Update modal on signup flow:

New card:
![image](https://user-images.githubusercontent.com/30194799/69626956-f8bcc800-1049-11ea-8e78-42710a3f3101.png)

Old card:

|Property | Value|
|------------ | -------------|
| Bundle ID | io.forus.me.test (49) |
| Device | iPhone 6S |
| Operating System | iOS 12.0 |
| Screen size | 4.7 in - 2.3 x 4.1 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d76dafc1e3d3ee1c57eba422c3cb4aa93d5ed9db/realios_iPhone_6S.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/d76dafc1e3d3ee1c57eba422c3cb4aa93d5ed9db/realios_iPhone_6S.jpg)

[Log URL](https://api.browserstack.com/applive/sessions/e6ed11ea1798ff7a57728fab3ef687bdb95f1298/devicelogs)

**Comment by maxvisser** [comment]
how would you make this less intrusive @jamalv

**Comment by jamalv** [comment]
![image](https://user-images.githubusercontent.com/30194799/69626956-f8bcc800-1049-11ea-8e78-42710a3f3101.png)

**Comment by maxvisser** [comment]
maybe user should start on profile page and the toggle goes blue (of crash reports) after pressing submit. So people see the setting aswell.

**Comment by jamalv** [comment]
Sure, I like the idea of letting people land on their profile page.  It makes more sense than an empty profile page.

**Comment by maxvisser** [comment]
*voucher page

**Comment by maxvisser** [comment]
Hi daniel is this fixed;
I tried build 57 and its not in testflight atleast.
