### ISSUE TITLE
Voucher Info button should land you on the voucher details page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#358]
## Context/goal: 
example url of a voucher details page:
https://dev.winterswijk.forus.io/#!/voucher/0xfc97f4c171b24087b76c1f7feb76270b3ed407f2

**Comment by SjoerdHilhorst** [comment]
Example of how it should be in android, and ios  [here.](https://www.figma.com/proto/oqd4vu78CL4cDahqaJ0L5q/Untitled?node-id=5%3A3&scaling=min-zoom)

**Comment by maxvisser** [comment]
@danieltcacenco @yasha fixes on frontend for this issue are on staging deployed. Could you look this again?

**Comment by maxvisser** [comment]
figma prototype is wrong (should land on voucher page)

**Comment by jknnr** [comment]
@maxvisser we are fine with this on the app side, all the info (url, token) comes from the server

**Comment by jknnr** [comment]
@maxvisser what should we do with this one?

**Comment by maxvisser** [comment]
in Andriod we implement his feature. It was not implemented yet in iOS.

**Comment by danieltcacenco** [comment]
could you show please full url how it should be

**Comment by maxvisser** [comment]
```
            val url: String = if (voucher?.fundWebShopUrl?.isNotEmpty()!! && vs.model.shortToken.isNotEmpty()) {
                voucher?.fundWebShopUrl + "auth-link?token=" + vs.model.shortToken + "&target=voucher-" + voucher?.address
            } else {
```
https://github.com/teamforus/me-android/blob/34671c3ff0346da40357b39fd48e1a65d67f7d28/presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherFragment.kt#L280

**Comment by danieltcacenco** [comment]
done
