### ISSUE TITLE
Implement Identity Service

### ISSUE THREAD

**Issue by martijndoornik** [teamforus/me#36]
Result of #35

The discussed protocol must then be implemented in a new Identity service.

**Comment by maxvisser** [comment]
key store
implement protocol
user access

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus.io/issues/62

**Comment by maxvisser** [comment]
This one is also deprecated as the same reason mentioned in: https://github.com/teamforus/me/issues/35
