### ISSUE TITLE
Me-ios: Debug functionality

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#364]
## Main asssignee: @

Task:
- [ ] add option to set any ip adress

## Context/goal: 

add ways to debug easily like:
storing multiple identities access tokens
changing base URL; adding custom local one

![Screenshot_20191216_165646_io forus test_meapp](https://user-images.githubusercontent.com/10818702/70922059-bcb3cc00-2025-11ea-8edf-cb510914175d.jpg)
![Screenshot_20191216_165857_io forus test_meapp](https://user-images.githubusercontent.com/10818702/70922064-bde4f900-2025-11ea-8214-05236e58274c.jpg)

**Comment by jamalv** [comment]
This issue needs refinement: how do you want to do this? only on certain environments? where do you want to put this functionality? It will not be in production, right?

**Comment by jamalv** [comment]
Should be able to set any IP adres for debugging

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
@danieltcacenco could you explain to me how it works via rc; can't find it

**Comment by maxvisser** [comment]
which app did you implemented this in; I could not find it in the test app.
