### ISSUE TITLE
iOS: Share bugreport textual change

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#376]
## Context/goal: 
**Title**: Informatie delen met de ontwikkelaars
**Description:** Door uw unieke identificatie nummer te delen met de ontwikkelaars, kan contact met u worden opgenomen om eventuele problemen op te lossen.

**Comment by GerbenBosschieter** [comment]
![fullsizeoutput_4a4](https://user-images.githubusercontent.com/38419514/71181801-2a096c00-2275-11ea-8874-931ba11c0eb1.jpeg)

**Comment by jamalv** [comment]
@danieltcacenco I think this is fixed? could you close the issue?

**Comment by danieltcacenco** [comment]
> @danieltcacenco I think this is fixed? could you close the issue?

yea its fixed, it was fixed before new year.
