### ISSUE TITLE
Implement better transaction Success modal

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#377]
## Context/goal: 

Userstory:
A user shows QR-code to provider and is in conversation.  The provider fills in amount and presses submit, app is loading, looks at citizen to again talk about the weather. Looks back at smartphone and there is no confirmation. This results in provider scanning voucher twice. A transaction success message was present but Provider did not see it as it goes away pretty quickly.

## Task
- [ ] Add a 'Succesfull transaction' confirmation modal after a transaction. It really important that he users presses submit/ OK before they can access scanner again.

Header title of modal: "Succes!"
Description: "Betaling geslaagd! De verwerking van de betaling kan maximaal 3 werkdagen duren."

**Comment by maestrovsmaster** [comment]
![device-2020-04-08-180920](https://user-images.githubusercontent.com/23098862/78800535-3a7c5880-79c4-11ea-974a-64cf877a447b.png)
Activity will be dismiss after click Ok button
