### ISSUE TITLE
Implement short token login 'voucher info'

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#379]
## Context/goal: 

implement a button on voucher to login on webshop of that voucher. The user sometimes want to see map of provider or other usefull voucher information.

## Task
- [ ] discuss with daniel how he implemented short tokens and retrieve short token to login on browser.
- [ ] implement 'Voucher Info' button on budgetvoucher details screen below email to yourself button

**Comment by jamalv** [comment]
if needed we can make a video of how this works on ios
