### ISSUE TITLE
Add price of reservation to payment screen.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#381]
## Context/goal: 
Current providers have problem with the way we handle reservation.
After they scan a product vouchers they are not informed of what price is going to be transferd to their bank account. This results into uncertainty and confusion of the payment it self.

### Task 
- inform the provider of what price is going to be transferd to their bank account.

**Comment by maxvisser** [comment]
should be checked on release of iOS v0.3.0

**Comment by maxvisser** [comment]
still not fixed

**Comment by danieltcacenco** [comment]
@maxvisser Could you help me with this task, because right now we have on confirm screen about "Please confirm the transaction of (price)".
