### ISSUE TITLE
About me button does does not show info

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/me#385]
## Context/goal: 
When on the profile tab in android. Pressing the "About Me" button does not do anything. In IOS it shows [this](https://www.figma.com/file/aHBFCcJKEm9ePO2lCjxbDo/Untitled?node-id=1%3A6)

**Comment by maestrovsmaster** [comment]
![device-2020-04-11-153630](https://user-images.githubusercontent.com/23098862/79043801-3b9ec700-7c0a-11ea-88d2-229dacb143c5.png)
