### ISSUE TITLE
Choose validator organisation when validating a personal record

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/me#386]
## Context/goal: 
In android, when you scan a qr-code of a property of a person there should be an option to choose as which validator you want to validate.

Currently in android:
![image](https://user-images.githubusercontent.com/48722300/73172980-8ed1a500-4104-11ea-8be1-15477152460d.png)

Example in ios:
![image](https://user-images.githubusercontent.com/48722300/73172550-904e9d80-4103-11ea-83ba-36e181995806.png)

**Comment by maxvisser** [comment]
https://zpl.io/2p7lnNl
