### ISSUE TITLE
On session destroy: give user a popup notice to logout me app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#388]
## Description

With the new sessions functionality a user can destroy Auth token on webshop/dashboard of me app

This issue is about gracefully logging out me app when Auth token is destroyed.

Gove user a popup notice:

EN: Your session has expired. You are being logged out.

NL: Deze sessie is verlopen. Je wordt nu uitgelogd.

## How to reproduce destruction of sessions

Login on http://dev.westerkwartier.forus.io
Using a signed in me app on base URL dev.api.forus.io

Go to http://dev.westerkwartier.forus.io/#!/security/sessions

Terminate session of me app

**Comment by maxvisser** [comment]
On android its not that gracefull yet. Popup should appear after scanning.

**Comment by maxvisser** [comment]
works on iOS

**Comment by maestrovsmaster** [comment]
![device-2020-04-06-153049](https://user-images.githubusercontent.com/23098862/78558908-1f6ee480-781c-11ea-83a3-9b1512ef5e33.png)

**Comment by maxvisser** [comment]
should also be displayed when scanning
