### ISSUE TITLE
Show validation success message when other me-app scan record QR-code

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#390]
## Context/goal: 

User flow: 
Other device scans QR-code of Me-iOS
Me-iOS polls backend for new validation request while QR-Code is visible.
Shows Validation success message when new validation request is approved.

**Comment by danieltcacenco** [comment]
This also should be link to backend.

**Comment by maxvisser** [comment]
Could you check android? As I like how it is implemented there @danieltcacenco do you still have android device? could you scan with me ios a record from android?

**Comment by maxvisser** [comment]
@jknnr this is working on android and also in Me-debug. If you need a video of the problem I can send you one.

Its currently not working on iOS

**Comment by danieltcacenco** [comment]
@maxvisser could you write please what message should be there i mean in english and dutch.

**Comment by jknnr** [comment]
@danieltcacenco 
on Android we used:
EN: Validation approved
NL: Validatie goedgekeurd

**Comment by danieltcacenco** [comment]
Done

**Comment by jknnr** [comment]
done
