### ISSUE TITLE
[Action Required] Fabric is shutting down March 31, 2020

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#394]
## Main asssignee: @

No specific tasks yet

## Context/goal: 
<img width="705" alt="Screen Shot 2020-02-11 at 15 21 41" src="https://user-images.githubusercontent.com/38419514/74245366-2d542d80-4ce3-11ea-9aaa-3663b6f4ab69.png">

**Comment by maxvisser** [comment]
Got this mail aswell

**Comment by maxvisser** [comment]
Test if it still works; migrate if needed (both apps)
