### ISSUE TITLE
Android: "Log me in" flow updates. 📱🛠

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#396]
@Myshelova has updated the signup flow for the me app. 

**Figma link**: https://www.figma.com/file/sDB8jUy4fM4oIdlPTL90nf/Log-me-in?node-id=50%3A19

_**The task is to implement this in the app.**_

- [x] update "1.mobile sign in" screen 
<img width="171" alt="Screenshot 2020-02-27 at 20 32 39" src="https://user-images.githubusercontent.com/32199937/75469608-5beb2d00-59a0-11ea-860e-cfbcd67e4f22.png">

- [x]  update "1.2mobile sign in" screen

<img width="243" alt="Screenshot 2020-02-27 at 20 37 18" src="https://user-images.githubusercontent.com/32199937/75469970-f9def780-59a0-11ea-8c57-92645f2f00c5.png">

- [x]  update "2.confirm" screen

<img width="235" alt="Screenshot 2020-02-27 at 20 38 12" src="https://user-images.githubusercontent.com/32199937/75470083-27c43c00-59a1-11ea-8650-a4758028d313.png">

- [x]  update "2.f.login_modal_qr" screen

<img width="237" alt="Screenshot 2020-02-27 at 20 38 20" src="https://user-images.githubusercontent.com/32199937/75470155-4a565500-59a1-11ea-8e9b-b7ecaf1db7ad.png">

- [x] update "3.Success" screen
<img width="234" alt="Screenshot 2020-02-27 at 20 43 41" src="https://user-images.githubusercontent.com/32199937/75470668-10d21980-59a2-11ea-9b54-b13535f483bb.png">

- [x] create "4. Share identification" screen
<img width="234" alt="Screenshot 2020-02-27 at 20 44 04" src="https://user-images.githubusercontent.com/32199937/75470771-38c17d00-59a2-11ea-8647-bd68875dfb87.png">

- [x] API update

- [x] make testing together with @jknnr

**Comment by jknnr** [comment]
tested, only needs english texts

**Comment by maxvisser** [comment]
could add anything you want changed to the translation issue?
