### ISSUE TITLE
Add missing translations

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#398]
## Context/goal: 
I've tested the app for upcoming release. And there are some missing translations. Did you setup your phone language settings to Dutch? It's just fine. Did you setup your phone language settings to English, will get an combination of Dutch and English aka Dunglish.

Almost all of the missing translations are occurring on the new screens we've added.

## Task
Please add all these translations and prevent using hardcoded texts.

### Missing translations
1. Share information with developers screen
2. Authorise / Connect device screen
3. Request for e-mail verification screen
4. Login succes screen
5. Home screen
6. About Me screen (missing wwebshops)

**Comment by GerbenBosschieter** [comment]
## Share information with developers screen
**Title:**  "_Sharing information_"
**Description:** _"By sharing your identification number, problems can be solved faster. If needed the developers can contact you as well"_
**Toggle**: _"Share identification number"_
**Button:** _"Next"_

<img src="https://user-images.githubusercontent.com/38419514/76746490-e04af780-6777-11ea-97ed-10fb434a7a78.PNG" alt="Share information with developers screen" width="200"/>

## Authorise / Connect device screen
**Title:**  "_Connect device_"
**Description:** _"This is your pairing code"_ or _"This your authorization code"_
**Sub_description:** _"Scan this QR-Code with a device you are already logged in"_
<img src="https://user-images.githubusercontent.com/38419514/76746489-dfb26100-6777-11ea-98d1-7cb4083b619d.PNG" alt="Authorise / Connect device screen" width="200"/>

## Request for e-mail verification screen
**Description:** _"Click on the link in the email you received to continue"
<img src="https://user-images.githubusercontent.com/38419514/76746486-df19ca80-6777-11ea-96e3-8789ceb22857.PNG" alt="Request for e-mail verification screen" width="200"/>

## Login succes screen 
**Title:**  "Successfully logged in"
**Button:** _"Next"_
<img src="https://user-images.githubusercontent.com/38419514/76746480-dcb77080-6777-11ea-9b96-eb3dbfbf3d19.PNG" alt="Login succes screen" width="200"/>

## Home screen (welcome to me)
*Input field:* _"Your email"_
*Description*: _"Log in from another device"_
<img src="https://user-images.githubusercontent.com/38419514/76746477-db864380-6777-11ea-967b-31bf16a02267.PNG" alt="Home screen" width="200"/>

## About Me screen (missing wwebshops)**
Add missing webshops to list
- Winterswijk
- Oost Gelre
- Berkelland
- Noordoostpolder

<img src="https://user-images.githubusercontent.com/38419514/76746484-de813400-6777-11ea-826d-dc1032d69644.PNG" alt="About Me screen" width="200"/>

**Comment by GerbenBosschieter** [comment]
@jamalv @maxvisser @jknnr @danieltcacenco If you have better english translations. Please use those.

**Comment by maxvisser** [comment]
Pairing code is nice

**Comment by jknnr** [comment]
i've been already working on texts, will finish today

**Comment by maxvisser** [comment]
done
