### ISSUE TITLE
Connection between MEapp Android and STEMapp Android 

### ISSUE THREAD

**Issue by TomForus** [teamforus/me#4]
**Connection between MEapp and the STEMapp on Android and Android**

## Prerequisites

- Do the Android version of STEMapp
- Do the Android version of MEapp

## Description

This issue has been made to create an connection between the MeApp and the StemApp on Android.

## Functional Design

1. To create an Intent in the MEapp
2. Let the user validate that he or she allows MEapp to make this connection with the STEMapp
3. The STEMapp needs to proces the data from the MEapp into the STEMapp

**User Story:** When you are in the STEMapp you click _'Vote'_. After you click _'Vote'_ the STEMapp sends a request to the MEapp and MEapp sends back the information about voting coins or voting tokens. If there are any. 

## Expected Version

Version 0.1

**Comment by martijndoornik** [comment]
- [ ] Create intent to receive external apps to communicate which attributes the external app needs from the Me App
- [ ] Let the Me App return the required data
- [ ] The Stem App processes data and knows whether a user can vote or not

**Comment by maxvisser** [comment]
I close this issue. The stemapp is currently not maintained by any developer therefore a connection can not be developed within a timeframe before august. If this gets relevant again. It can be reopened.
