### ISSUE TITLE
API update for the multiple emails

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#406]
The new functionality of connecting multiple emails is going to be introduced.

Updates with 3 endpoints are requested:

1. `registration`
2. `auth-email-request`
3. use `identity` instead of `records-list` to get the current primary email

**Comment by maestrovsmaster** [comment]
Привет. У провайдера интернета какие-то работы сегодня до 18ти. Интернет
работает нестабильно. Какие-то сервисы работают, какие-то нет. Скайп и
гитхаб , например, периодичски отваливаются. В общем, я задачу по апи
вчерашнюю сделал, но там бы еще неплохо было бы потетсить, но пока не могу
залить на гит, он у меня не работает
ср, 25 бер. 2020 о 19:38 yasha <notifications@github.com> пише:

**Comment by danieltcacenco** [comment]
Done
