### ISSUE TITLE
No matching error message after scanning voucher

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#409]
## Context/goal:
**Branch:** Release/v0.2.0 

Provider gets no matching error message after scanning budget voucher while not being accepted for the fund.
App displays an failure page with: Failed, try again

**Task**
Please add matching error tho this scenario (provider not accepted but scans budget voucher)
Error is already in the code base.

Please add error: qr_voucher_access_denied from strings.xml to this scenario.

**Comment by maxvisser** [comment]
As I understand no error have to be added to the me-app as we should always try to return the one from backend.
