### ISSUE TITLE
Design updates for Records

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#419]
- [ ] 1. iOS needs a design to change profile tab for records, and how to enter the profile then.

- [ ] 2. Android: the same as for iOS + refactor the screens for records (list with validation count), screen of each record and more if needed.

**Comment by maxvisser** [comment]
https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/Prototype---Me-App---Android?node-id=191%3A8
