### ISSUE TITLE
Fix UI elements after X-Code update

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#420]
Today while working on records, we realised that UI got broken in multiple places. 
Look:
![2020-04-27 17 02 45](https://user-images.githubusercontent.com/32199937/80381002-f4226700-88a8-11ea-9721-11f0db7ec3f7.jpg)

The problem came after the latest xcode update. 

The task is to test all screens and fix where it needed.

**Comment by danieltcacenco** [comment]
done
