### ISSUE TITLE
Implement updated records

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#421]
Records screens have been updated. Should be implemented now.

Link to the screens:
https://www.figma.com/file/T8neLdRpJblct0A6eiToNL/Prototype-%E2%80%93-Me-App-iOS?node-id=77%3A5482

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
Max needs to review texts:
https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/Prototype---Me-App---Android?node-id=191%3A8

**Comment by jknnr** [comment]
done
