### ISSUE TITLE
New user uses pairing code to sign up but don't get registration successfull message

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#425]
## Context/goal: 
*explain why this issue was opened*

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
pr seems to not contain any code. I merged the pr. could you check if it works @danieltcacenco

**Comment by maartenfv** [comment]
@danieltcacenco Could you please briefly write down your progress when writing hours on an issue?

**Comment by jknnr** [comment]
done
