### ISSUE TITLE
Make screenshots of Nokia One and enhance the app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#426]
## Context/goal: 
As Nokia One is a small form factor some pages don't look that great. We want to enhance the Me-app for smaller resolution. We will start with screenshot and add them to figma.

We use comments to have discussion about improving the pages and make proposal to enhance.

**Comment by jknnr** [comment]
![2020-05-12 12 59 47](https://user-images.githubusercontent.com/32199937/81670568-7fc2f880-9450-11ea-87ab-64e585a6eae8.jpg)
![2020-05-12 12 59 43](https://user-images.githubusercontent.com/32199937/81670577-818cbc00-9450-11ea-9050-e71c79f5f5cd.jpg)
![2020-05-12 12 59 40](https://user-images.githubusercontent.com/32199937/81670584-8487ac80-9450-11ea-8190-cfde30db7608.jpg)
![2020-05-12 12 59 35](https://user-images.githubusercontent.com/32199937/81670593-86517000-9450-11ea-9da9-19538b04747c.jpg)

**Comment by jknnr** [comment]
There is also a video, that I can't add, we worked on adding the scroll on the qr code for nokia 1 to see all the voucher info that is written under the qr

**Comment by maxvisser** [comment]
On a bigger screen the offset of the title is even more noticable
