### ISSUE TITLE
Check google maps in me-android/ios

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#428]
## Context/goal: 
On staging the app does not load the map. We should check if it is working on production.

**Comment by danieltcacenco** [comment]
i tested and its ok.

**Comment by jknnr** [comment]
@maxvisser still need the access to google developer console

**Comment by GerbenBosschieter** [comment]
Already told you that I don't have acces to this. Never heard of it, never seen it. And if I log I see an empty dashboard.

**Comment by maxvisser** [comment]
> Already told you that I don't have access to this. Never heard of it, never seen it. And if I log I see an empty dashboard.

I wanted to discuss this with you. I would just like to login on Me-app android on production on an account which has a product voucher (and just check if it has G-Maps working); I see the developer console as second stage.

**Comment by maxvisser** [comment]
Checked on production. Me-androids google maps is not working. Should fix this on next release

**Comment by maxvisser** [comment]
call with @jknnr @maestrovsmaster @maxvisser

**Comment by maestrovsmaster** [comment]
i used my own demo api key and google maps is work.  But it is temporary solution, we must use forus api keys
![device-2020-07-29-185707](https://user-images.githubusercontent.com/23098862/88823057-530bbb00-d1cd-11ea-9833-224db116f3db.png)

**Comment by maxvisser** [comment]
I can easily create these in google cloud console. I know there is a file which contains this key but not sure anymore who created this initial key.

**Comment by maestrovsmaster** [comment]
I think, we must have more than one key:  keys for api.forus.io , dev, staging

**Comment by jknnr** [comment]
done
