### ISSUE TITLE
Android: Let Google host our singing key

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#429]
## Context/goal: 
Google offers a service to host you singing key.
When building a APK for release we have to provider this key with the right credentials.

Hosting the key ourself wil probably and already did result in some problems:
- Saving the key locally is very risky (what if there person leaves, computer crashes, etc etc.)
- We already tried to save it in the cloud but this resulted in a corrupt file.

## Task
Let Google host our singing key just like apple does with certificates.

**Comment by maestrovsmaster** [comment]
Yes, thee best approach would be to use Bundle instead APK files.
https://support.google.com/googleplay/android-developer/answer/7384423?hl=en

**Comment by jknnr** [comment]
@maxvisser can we close this?

**Comment by maxvisser** [comment]
Yes it's done

**Comment by jknnr** [comment]
done
