### ISSUE TITLE
re-add submodule

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#43]
## Context/goal: 
This repo was becoming a bit of a clucterfck. It was 2gb to clone while it is actually mostly empty. I created a develop branch without commit history (I think this used to host both iOS and android apps). But now the  https://github.com/teamforus/me-ios and https://github.com/teamforus/me-android submodules are gone, could you re-add them?

**Comment by maxvisser** [comment]
Yes will do:)

**Comment by maxvisser** [comment]
done
