### ISSUE TITLE
Look for QR-code dependency which can display images inside QR

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#433]
## Context/goal: 

Would be nice to show on pairing QR-code a me logo.
![image](https://user-images.githubusercontent.com/10818702/81555147-4757e780-9388-11ea-9312-0bc90383f41e.png)

**Comment by jknnr** [comment]
@maxvisser possible, just need to place the icon on server

**Comment by maxvisser** [comment]
https://media.forus.io/assets/me-logo.png

**Comment by jknnr** [comment]
@dev-rminds not an urgent task but we need a field in the pairing qr-code, to add an icon inside
smth like: 
```
{
"voucher":"fgdfgdsfgdsg"
"company":"asdasd"
"imgUrl":"http://icon.png"
}

```

**Comment by maxvisser** [comment]
the image will not change so it can be hardcoded or even added to the build

**Comment by maestrovsmaster** [comment]
Now in android we use this library https://github.com/kenglxn/QRGen for QR code.
Unfortunately, possibility to add custom logo most likely not currently provided 
https://github.com/kenglxn/QRGen/issues/132

**Comment by maxvisser** [comment]
@maestrovsmaster I see that this dependency is a API wrapper for [ZXING](http://code.google.com/p/zxing/)

some things I found:
https://aboullaite.me/generate-qrcode-with-logo-image-using-zxing/
https://skrymerdev.wordpress.com/2012/09/22/qr-code-generation-with-zxing/

**Comment by maestrovsmaster** [comment]
![device-2020-07-20-192756](https://user-images.githubusercontent.com/23098862/87962367-be63d780-cabf-11ea-8e20-4a1473094535.png)

**Comment by maestrovsmaster** [comment]
> @maestrovsmaster I see that this dependency is a API wrapper for [ZXING](http://code.google.com/p/zxing/)
> 
> some things I found:
> https://aboullaite.me/generate-qrcode-with-logo-image-using-zxing/
> https://skrymerdev.wordpress.com/2012/09/22/qr-code-generation-with-zxing/

This solutions are for java desctop and not supported by android, but i was created own solution for android, based on this java solution
