### ISSUE TITLE
Show a euro symbol before each amount

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#436]
Requested by:
Jamal

Change description
Right now we display numbers as:

5

it should be formatted nicer e.g.

€5,-

or

€5,00

or

€5,25

Please be aware. Here in the netherlands we don't use smaller numbers (superscript) to show decimals.
![82199567-251d1700-98fe-11ea-89b1-6370496e2325](https://user-images.githubusercontent.com/32199937/82223638-91fad600-992b-11ea-891e-f0f6cadc60aa.jpg)

**Comment by danieltcacenco** [comment]
done
