### ISSUE TITLE
Switch environment inside the app

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#437]
We have a very useful implementation of this feature on iOS that saves time on testing. 
It is needed is you want to swap dev to staging without creating a new build and sending it over.

**Comment by maxvisser** [comment]
Yes I would like to add a way to add custom api

**Comment by jamalv** [comment]
there is a status endpoint on the api
api/v1/status if api returns 200 api is ok

**Comment by jknnr** [comment]
done
