### ISSUE TITLE
Records Create/Archive

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#438]
Android: https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/Prototype-Me-App-Android?node-id=328%3A0

iOS: https://www.figma.com/proto/T8neLdRpJblct0A6eiToNL/Prototype-%E2%80%93-Me-App-iOS?node-id=394%3A4&scaling=min-zoom

**Comment by danieltcacenco** [comment]
we need backend for thi

**Comment by jknnr** [comment]
This one is to be refined more. The proposal is to keep an archive without an ability to edit the record.
