### ISSUE TITLE
Product vouchers: App displays wrong organisation name

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#440]
## Context/goal: 
Me-app displays name of the organization who granted the budget vouchers instead of the provider who offered this product.

## Task
- Display name of the provider instead of the organisation who provided the fund
See image below, provider name is Upper but it says Gemeente Berkellenad

![IMG_0043](https://user-images.githubusercontent.com/38419514/83851563-db606900-a712-11ea-8e5c-6e3b2aa4afed.jpg)

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
On list it is fixed but on details still the wrong information is displayed.

**Comment by danieltcacenco** [comment]
its done, change in voucher table view cell organization name in dependence of voucher type, the same made fo detail product voucher.

**Comment by jknnr** [comment]
done
