### ISSUE TITLE
Textual change: Uw email

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#441]
## Context/goal: 
The sign up page will ask you to fill in your mailadres. But the way this is spelled is wrong in dutch.

### Task
- Change text
    - **From:** Uw email
    - **To**: Uw e-mailadres

![IMG_0340](https://user-images.githubusercontent.com/38419514/83886489-6c513780-a747-11ea-8852-ebad12bc40ac.PNG)

**Comment by maxvisser** [comment]
on Android it is just 'E-mail'

**Comment by GerbenBosschieter** [comment]
@maestrovsmaster Could you fix this on android also?

Should be: Uw e-mailadres

**Comment by danieltcacenco** [comment]
done

**Comment by jknnr** [comment]
done
