### ISSUE TITLE
Bug: Additional payment in case of insufficient budget is no longer possible

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#442]
## Context/goal: 
If a requester had a budget of € 196.- but wants to buy something of € 200,- it would be normally possible because the Me-app would give a message about the insufficient amount and asks if the requester wants to do an additional payment of the missing amount (in this € 4.-)

The provider confirms the payment, the 196 wil be transferred and the other 4 euro is being payed by the requester it self.

This doesn't work anymore. After submitting the provider will get a error instead of succes message.

## Task
- The app should process the transaction instead of giving an error.

**Example of the message**
![IMG_0343](https://user-images.githubusercontent.com/38419514/83886880-f7323200-a747-11ea-915b-29661f384b96.PNG)

**Example of the error after submitting (not enough budget on voucher)**
![IMG_0341](https://user-images.githubusercontent.com/38419514/83887403-abcc5380-a748-11ea-9238-38ab6ca84493.PNG)

**Comment by maxvisser** [comment]
which version of the app is this?

**Comment by jknnr** [comment]
on it

**Comment by GerbenBosschieter** [comment]
@maxvisser All of them. It's currently bug.

**Comment by danieltcacenco** [comment]
This error comes from server, i got error 422: 
<img width="562" alt="Screenshot 2020-06-14 at 12 24 09" src="https://user-images.githubusercontent.com/9008175/84589826-08f79180-ae3a-11ea-8c72-a360c0cf2215.png">

**Comment by maxvisser** [comment]
what do you sent to the backend? As you should sent the 196 (instead of the 200)

@GerbenBosschieter could you reproduce it on android?

**Comment by GerbenBosschieter** [comment]
Tested it on Android. Works just fine. 
@danieltcacenco could you fix this?

**Comment by danieltcacenco** [comment]
ok, thanks

**Comment by danieltcacenco** [comment]
Fix issue in ConfirmPaymentPopUp, fix logic of calculation if sum introduced is bigger than budget voucher, and tested.

**Comment by jknnr** [comment]
done
