### ISSUE TITLE
Tooltips for records

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#444]
functions like archiving records. 

Tooltips to give an introduction to a new function. Show the user where to find for example archived records.

**Comment by Myshelova** [comment]
### Tooltips

**What is:** _Tooltips to give an introduction to a new function_

Figma prototype:
iOS https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/Prototype-Me-App---iOS?node-id=1098%3A11364
Android https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/Prototype---Me-App---Android?node-id=525%3A309

When we will show them:

**1. Dialog sheet**
When the user edits or archives their record for the first time, we will show this dialogue sheet.

If the user clicks the "Go to archive" button, the list of archived records screen opens
If the user will tap on “ok” we will close this dialogue sheet 
![image](https://user-images.githubusercontent.com/22478043/86002379-8c0b1100-ba10-11ea-8ec7-7e593bfd4435.png)


**2. Tooltips**
These tooltips should be hidden 30 seconds after opening the proper screen

a. Archive
When the user will add his first record into an archive and goes back to the records screen we will show him this tooltip. 
![image](https://user-images.githubusercontent.com/22478043/86002410-962d0f80-ba10-11ea-9994-685fbfdeb893.png)

b. Edit records
We will show this tooltip when the user will open the record details screen for the first time
![image](https://user-images.githubusercontent.com/22478043/86002444-a218d180-ba10-11ea-8158-aaae8fb401dc.png)
