### ISSUE TITLE
Me-app isn't aligned with backend limitations considering expired vouchers (My assumption)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#448]
# Description

There was a backend change a while ago that set limitations for expired vouchers to prevent problems and confusion for people who received a voucher for the new calendar year.

- Users couldn't open the voucher anymore (QR Code is hidden, transactions are still displayed)
- Users couldn't send the voucher to themself anymore by mail.

## Me-app
All these features and visual parts are still a thing in the Me-app. While backend is limiting it.

**iOS**: Shows succes message after sending the voucher to yourself. But of course no e-mail is being send.
**Android**: Shows confirmation message and asks if you want to send it to yourself. After confirming this you will get aan error: Failed.

### Task
Can't think of any task do quick fix this and don't really think a quick fix is needed. 
Would be nice if you guys can help with thinking of a solution.
This will influence some screens, so needs designs and some refinements.
I will create a Change request. Current state is not really acceptable but no users mentioned this.

#### Additional information
Do you want to reproduce this? I can give you acces to my profile (production) It has a a christmas voucher that is expired.

**Comment by maxvisser** [comment]
quickfix could be to hide expired vouchers in Me-app

**Comment by danieltcacenco** [comment]
ok, i think we should get some decision and figure it out.

**Comment by danieltcacenco** [comment]
@maxvisser @GerbenBosschieter @jknnr  so, what we decide, hide expired voucher or do something else?

**Comment by maxvisser** [comment]
I would hide the vouchers for now until new screens are made. Adjusting these pages (without QR-code, without the buttons) probably need some time.

**Comment by jknnr** [comment]
It is ready on android, will fix for ios very soon

**Comment by maxvisser** [comment]
Is it fixed on iOS?

**Comment by jknnr** [comment]
Fixed on both
