### ISSUE TITLE
Fix Login By FaceID

### ISSUE THREAD

**Issue by danieltcacenco** [teamforus/me#451]
## Context/goal: 
check on device where is face id, right now is not working.

**Comment by danieltcacenco** [comment]
Need translate for:
''Unlock with %@'' 
"Authentication Failed"
"User Cancel"
"System Cancel"
"Please go to the Settings & Turn On Passcode"
"%@ Dont Available"
"%@ Not Enrolled"
"%@ Lockout Please goto the Settings & Turn On Passcode"
"App Cancel"
"Invalid Context"

**Comment by maxvisser** [comment]
@maartenfv @linda-90 Could translate these texts; these are errors/message which appear in context of FaceID. There is no figma prototype;  It are Apple / iOS native system messages.

**Comment by linda-90** [comment]
@maxvisser Klopt dit? Ik weet niet waar %@ voor staat?

- ''Unlock with %@''
    - "Ontgrendelen met %@"
- "Authentication Failed" 
    - ''Authenticatie mislukt'
- "User Cancel" 
    - "Gebruiker annuleren"
- "System Cancel"
    - Systeem annuleren"
- "Please go to the Settings & Turn On Passcode" 
    - "Ga naar instellingen en schakel toegangscode in"
- "%@ Dont Available" 
    - "%@ Niet beschikbaar"
- "%@ Not Enrolled" 
    - "%@ Niet ingeschreven"
- "%@ Lockout Please goto the Settings & Turn On Passcode" 
    - "%@ Vergrendeld. Ga naar instellingen en schakel de toegangscode in"
- "App Cancel" 
    - "App annuleren"
- "Invalid Context" 
    - "Ongeldige context"

**Comment by danieltcacenco** [comment]
done, thanks
