### ISSUE TITLE
Parse the json from the old cards

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#452]
Context:

We read our vouchers like this {"type":"voucher","value":"0xeaf87a4fcecd4b505973cdefae4362ac09f6bb98"}.

What we need is to read the 12-digit number from the old card, parse it to json and send it to the backend like {"type":"voucher","value":"100199180188"}

The old card looks like this.
![image](https://user-images.githubusercontent.com/32199937/87289262-166d6d80-c505-11ea-8362-58d7d403711a.png)

**Comment by GerbenBosschieter** [comment]
![IMG_8C1049C87265-1](https://user-images.githubusercontent.com/38419514/89405768-5f879a80-d71c-11ea-9b4f-ba556f36cf6b.jpeg)

**Comment by jknnr** [comment]
done
