### ISSUE TITLE
QR-code popup shows english date instead of dutch

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#459]
## Context/goal: 
Date is in English localization
![image](https://user-images.githubusercontent.com/10818702/88286633-572d6980-ccf1-11ea-871b-861b2a6d5f34.png)

Months should be translated January should be Januari

laat -> Laat (First letter of a sentence should be a Capital)

**Comment by maestrovsmaster** [comment]
This
![device-2020-07-23-201726](https://user-images.githubusercontent.com/23098862/88317911-9f18b480-cd22-11ea-867e-4e8242ddd7a4.png)
 date depends on the server api variable ( "expire_at_locale": "1 januari 2021", checked on staging server)

**Comment by maxvisser** [comment]
There it is Januari and not January?

**Comment by maestrovsmaster** [comment]
![Знімок екрана 2020-07-24 о 11 43 32](https://user-images.githubusercontent.com/23098862/88374725-e8a8e400-cda2-11ea-8fa7-b743cdcc70d5.png)

**Comment by maxvisser** [comment]
Allright. Seems that our development environment returns here January instead of Januari. Will close this issue.
