### ISSUE TITLE
Actions implementation

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#461]
Actions are the new type of vouchers.

The iOS designs are here under the Master tab https://www.figma.com/file/9oXhiRQLvFu1FJ7jeUj3n9/Me-Actions-checkout?node-id=93%3A0
<img width="454" alt="Screenshot 2020-07-29 at 14 15 52" src="https://user-images.githubusercontent.com/32199937/88793762-082a7d00-d1a6-11ea-8192-7383bfc78a27.png">
<img width="626" alt="Screenshot 2020-07-29 at 14 16 09" src="https://user-images.githubusercontent.com/32199937/88793782-1082b800-d1a6-11ea-850a-9aa2c5aa7a59.png">

Android (Actions tab): 
https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/Me-Android?node-id=756%3A0

**Comment by maestrovsmaster** [comment]
demo preview
![device-2020-09-02-002307](https://user-images.githubusercontent.com/23098862/91912687-632b2480-ecbc-11ea-83de-8af2097a1b11.png)
