### ISSUE TITLE
Expired voucher text change

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#466]
## Context/goal: 
`Gebruik deze voucher voor 1 juni 2020` should be:
`Deze voucher is verlopen op 1 juni 2020`

![image](https://user-images.githubusercontent.com/10818702/89160068-c405f680-d570-11ea-95b6-1cec4bbf8f18.png)

**Comment by maxvisser** [comment]
current text means 'Use this voucher before xx` which does not indicate that voucher is expired.

**Comment by jknnr** [comment]
@maestrovsmaster 
Actual voucher:
  -en Use this voucher until {date}
  -nl  Gebruik deze voucher voor {date}
Expired voucher:
 -en This voucher expired on {date}
  -nl Deze voucher is verlopen op {date}

**Comment by jknnr** [comment]
done
