### ISSUE TITLE
Discuss about difference between api of dev and staging

### ISSUE THREAD

**Issue by danieltcacenco** [teamforus/me#468]
## Context/goal: 
We need to discuss why api of register and login by email is different. Because right now dev and staging with prod have different logic.

**Comment by maxvisser** [comment]
on DEV we have this configured:
DISABLE_DEPRECATED_API=true

**Comment by maxvisser** [comment]
on STAGING we have this configured:
DISABLE_DEPRECATED_API=false

on PRODUCTION we have this configured:
DISABLE_DEPRECATED_API=false

**Comment by maxvisser** [comment]
No need for backend fix. iOS has a fixed branch which can be merged.

**Comment by maxvisser** [comment]
test 0.3.0 (nice to check)
