### ISSUE TITLE
Change feedback to support

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#476]
@GerbenBosschieter commented on [Tue Jun 23 2020](https://github.com/teamforus/general/issues/249)

Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [ ] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
- feedback@forus.io is currently being used to send message to us via the Me-app. This mail should is created to receive feedback but is being used to ask questions. The mails send via the Me-app are sent to support and some team members with the intention to receive and process feedback and if a question is being asked it can be answered by support.

## Desired situation
- use support@forus.io instead of feedback@forus.io. Inform the users by telling them something like: Do you have any questions or feedback? Contact us!

My assumption is that all the people who are connected feedback@forus.io are already experiences these mails as spam cause most of it is just support.

In addition, we did some restructuring of how we process information from support so no feedback or change request from users perspective will be lost :D

## Plan
- Change mailadres and text in Me-app
- @maxvisser remove feedback@forus.io

done

---

@maxvisser commented on [Wed Jun 24 2020](https://github.com/teamforus/general/issues/249#issuecomment-648712140)

@jknnr this can be planned

---

@jamalv commented on [Tue Aug 11 2020](https://github.com/teamforus/general/issues/249#issuecomment-672211457)

@jknnr could you give a status update of this issue?

**Comment by jamalv** [comment]
AFAIK this has been fixed
