### ISSUE TITLE
Make Design proposal: Adding more offices  to product voucher in Me-app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#479]
## Context/goal: 
CR:
https://github.com/teamforus/general/issues/115

Currently when a organisation has multiple offices we should the latest added office. As a provider can have multiple locations where the product can be picked up, we should show them all on the product voucher.

A provider organisation has:
- A e-mail address *optional
- A telephonenumber*optional
- Website*optional

A office has these attributes:
- A location (LAT/LON) and address 
- A telephonenumber *optional
- Openingtimes *optional

Lets show a title above the map. NL: 'Vestigingen' EN: 'Offices'
Show below this tile multiple cards with a map of the location, a telephone number and opening times per location.

How to show openingtimes?
![image](https://user-images.githubusercontent.com/10818702/54308827-1d156900-45cf-11e9-8967-3a3a79fd90d6.png)

## Design / UI
On website we want to show it like this:
![image](https://user-images.githubusercontent.com/10818702/54355057-69f15200-4658-11e9-8f4d-a805cff003e9.png)

In app we currently only show one office:
![image](https://user-images.githubusercontent.com/10818702/92694064-c6652880-f346-11ea-91a2-c3bf8ef67510.png)

**Comment by jamalv** [comment]
Figma: https://www.figma.com/file/Lsr81BsvQfF1auzt6OnTJF/Untitled?node-id=1%3A421

**Comment by maxvisser** [comment]
@jknnr this is needed on product voucher; currently it only shows one office

**Comment by maxvisser** [comment]
Discussed it briefly with @Myshelova after she is done with #453; she will make two proposal for the developers to pick from. One question to explore with developers is how dynamically the map can be previewed (aswell with multiple pins.)
