### ISSUE TITLE
Reponsiveness Me app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#48]
## Main asssignee: 
@jknnr - pm
@kremlinwarrior - Android
@danieltcacenco - iOS

## Context/goal: 
https://github.com/teamforus/forus/issues/94

As the me app will be installed on multiple iPhone versions and probably low-end Android devices at 1 nov 2018. We need to start to test responsiveness on all devices and implemented some backwards compatibility.

**Comment by jknnr** [comment]
For iphone we support versions starting from iOS 8 (current is 12)
Android is starting from v4.3, (fingerprints starting from 6, otherwise it will not be shown)
Tested.
