### ISSUE TITLE
Backwards compatibility: Next backend release could break user experience 

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#481]
## Context/goal: 
Reproduce:
- What is exaclty the problem
- What devices?
- What app and backend version

**Comment by GerbenBosschieter** [comment]
Will reproduce for ios

**Comment by maxvisser** [comment]
Should try to reproduce it on an account without any action vouchers ;)

**Comment by maxvisser** [comment]
We found two bugs.
