### ISSUE TITLE
Actions: Textual change Pay €0 at the cash register

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#485]
## Context/goal: 
If an action is free the current text used in Me-app is "Let the requester pay €0 at the cash register"
It would be better to tell the provider that the requester does not need to pay anything.

NL: "Deze actie is gratis, er hoeft niet bijbetaald te worden."

**Comment by jknnr** [comment]
EN: This product is free, no additional payment is required.

**Comment by maestrovsmaster** [comment]
![image](https://user-images.githubusercontent.com/23098862/95981384-3b84bb80-0e27-11eb-8029-7ace8f071720.png)

**Comment by jknnr** [comment]
done
