### ISSUE TITLE
iOS: App crashes if there is a reservation (product voucher) and stock amount is on 1

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#494]
## Context/goal: 
This bugs happens on all environments including the master branch.
@danieltcacenco Could you fix this bug on master branch and create PR to Master and develop?

**Steps to reproduce**
- You need a profile that has a budget voucher and a product voucher.
- You need to have a product voucher that has only has a stock of only 1

1. Open app
2. Scan QR code requester (doesn't matter if you choose budget or product voucher)
3. You get an error like the image below
4. Error tells user that that product is sold out while in reality there is still 1 left in stock.

![IMG_405A303D4738-1](https://user-images.githubusercontent.com/38419514/96413853-9124e380-11ec-11eb-8425-e836c8e99138.JPG)

**Comment by jknnr** [comment]
@GerbenBosschieter can we close this?
