### ISSUE TITLE
iOS: Missing translations or text

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#496]
## Context/goal: 
There are some missing translations. Please add these translations.

**1. Transaction tooltip**
English: "Tap here if you want to see your list of transactions"
Dutch: "Druk hier als je de lijst met transacties wilt openen"

![IMG_1070](https://user-images.githubusercontent.com/38419514/96887739-28a46380-1485-11eb-93eb-5a25696393a7.PNG)

**2. Transaction list & date picker (providers)**
English: "Choose from date"
Dutch: "Zoeken op datum"
English: "pending"
Dutch: "In afwachting"
English: "success"
Dutch: "voltooid"

![IMG_1072](https://user-images.githubusercontent.com/38419514/96889792-3eb32380-1487-11eb-86cd-d5918cbb6e12.PNG)
![IMG_1071](https://user-images.githubusercontent.com/38419514/96889805-4377d780-1487-11eb-9411-9f2622874d34.PNG)

**Comment by danieltcacenco** [comment]
Done
