### ISSUE TITLE
iOS: Records page has been added to menu instead of profile?

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#498]
## Context/goal: 
I noticed that the menu tab now has now the record tab back in the menu. This was profile before.  Not sure why this was switched around again and if it was requested.

Users will not actively use records yet so I would like to request to switch this arround again.
- Add profile tab back to the menu
- Add records page behind e-mailadres of user 

![IMG_1070](https://user-images.githubusercontent.com/38419514/96890817-517a2800-1488-11eb-9419-701d248d23f5.PNG)

**Comment by danieltcacenco** [comment]
its weird because we already have design approved for that.

**Comment by GerbenBosschieter** [comment]
@jamalv or @maxvisser  this was done because of an approved design https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/Me-iOS?node-id=1565%3A0

What do you guys want to do with this?

**Comment by jamalv** [comment]
In the upcoming release (0.4.1) we will keep it as it is, in the next release (0.5) we are planning to add the privacy statement and onboarding screens and to also make the switch back, so for now it will stay as it is.
