### ISSUE TITLE
iOS: Hide text about that user has to do an extra payment if it's not the case.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#499]
## Context/goal: 
This text should only be shown if the user has to do an extra payment. It's currently shown all the time.
Title: **Kies een actie**
Description: "Let op: de klant moet het bedrag aan de kassa betalen"

![IMG_B71878034DFA-1](https://user-images.githubusercontent.com/38419514/96892101-98b4e880-1489-11eb-80bf-b37c3eb63b94.jpeg)

**Comment by GerbenBosschieter** [comment]
@jamalv @maxvisser @jknnr could you help Daniel to explain how he can implement this. I don't know my self

**Comment by GerbenBosschieter** [comment]
For Android this issue was used: https://github.com/teamforus/me/issues/487

@jknnr you know how vasily implemented it? could you explain daniel?

**Comment by jamalv** [comment]
If this was already implemented on android I'm not sure what actions I can take. @jknnr could you make sure this is taken care of? 🚀

**Comment by jknnr** [comment]
checking

**Comment by maxvisser** [comment]
needs to be reproduced (if still an issue) on reviewing me checkout @GerbenBosschieter

**Comment by maxvisser** [comment]
@GerbenBosschieter / @jamalv / @jknnr could you very if this is the case on iOS

**Comment by jamalv** [comment]
verified that it's been removed
