### ISSUE TITLE
iOS: Payment screen after scanning Qr code is changed

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#500]
## Context/goal: 
The payment screen looks different. No clean distinction between the field where you can enter the price and the field where you can add a note.

Please change this back how it was before.

![IMG_21CB7701A13E-1](https://user-images.githubusercontent.com/38419514/96893730-4e346b80-148b-11eb-8148-ce88ec87d183.jpeg)

**Comment by danieltcacenco** [comment]
Done
