### ISSUE TITLE
iOS: Where are those beautiful scrolling animations animations :(

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#502]
## Context/goal: 
@danieltcacenco you added these beautiful animation when a users scrolls through the transaction list. but they are gone now :( Would be nice to have them back.

https://drive.google.com/file/d/1G73WZNpkudTNzvKYlAC2CV5Co_kflleX/view?usp=sharing

**Comment by danieltcacenco** [comment]
> ## Main asssignee: @
> 
> 
> 
> ## Context/goal: 
> 
> @danieltcacenco you added these beautiful animation when a users scrolls through the transaction list. but they are gone now :( Would be nice to have them back.
> 
> 
> 
> https://drive.google.com/file/d/1G73WZNpkudTNzvKYlAC2CV5Co_kflleX/view?usp=sharing
> 
> 

That appear when voucher have 10 transction or more

**Comment by GerbenBosschieter** [comment]
Aaa oke, than i will close this one :)

**Comment by Myshelova** [comment]
Guys, sorry for bothering, but we should scroll all screen content, not only transactions. How this screen scroll should look like you can see at this example of the new concept of product voucher: https://drive.google.com/file/d/1u0NxAnCuFLp1j2n0z4wRVScz9dD0NeUt/view?usp=sharing
