### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#505]
Profile:
![image](https://user-images.githubusercontent.com/32199937/97553111-188d0680-19e6-11eb-9081-a8c10389c05a.png)

Record details:
![image](https://user-images.githubusercontent.com/32199937/97551634-45d8b500-19e4-11eb-9659-d8c7686e24d4.png)

Check colours on those buttons text:
![image](https://user-images.githubusercontent.com/32199937/97553646-c3052980-19e6-11eb-9c63-8e42f0f31ee6.png)

The tooltip will show up every time:
![image](https://user-images.githubusercontent.com/32199937/97553723-da441700-19e6-11eb-940e-1c77b1107112.png)

Euro Cents should be down:
 ![image](https://user-images.githubusercontent.com/32199937/97553749-e29c5200-19e6-11eb-8b16-ad98b1f3656a.png)

**Comment by jamalv** [comment]
@jknnr @danieltcacenco what's the status? can this be closed?
