### ISSUE TITLE
Me records privacy: Tekst review

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#508]
@jamalv commented on [Mon Nov 02 2020](https://github.com/teamforus/general/issues/561)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a user I would like to be informed about my privacy in the me app.

Figma: https://www.figma.com/file/TQMxcPx7ANAldafD9seRsF/?node-id=1%3A80

**Comment by maxvisser** [comment]
@linda-90 before starting development we still are waiting for text review. if you have time could you check this? (close the issue if you are already done)

**Comment by linda-90** [comment]
@maxvisser Mail over gestuurd. Krijg vandaag de nieuwe tekst toegestuurd.

**Comment by linda-90** [comment]
@maxvisser heb de nieuwe tekst binnen:

**Privacy** 

Bij het aanvragen van de Stadjerspas worden de volgende gegevens opgeslagen.  

**E-mailadres** 
Deze is nodig om je account aan te maken en te zorgen dat je straks toegang hebt tot je account 

**Burgerservicenummer (BSN)** 
Hiermee zoeken wij jouw gegevens op en hoef je niet steeds opnieuw je gegevens in te vullen. 

**Inkomensgegevens** 
Hiermee kunnen wij zien of jij recht hebt op een Stadjerspas.   

**Aantal kinderen** 
Thuiswonenden kinderen tot 18 jaar worden automatisch bijgeschreven op je account. 
 
**Stadjerspas uitgaven en tegoeden** 
Hiermee kun je zelf zien wat je hebt gebruikt en hoeveel tegoed je nog over hebt.  Ook de aanbieder en de gemeente Groningen zien wat er is verbruikt. Maar zij kunnen niet zien dat dit jouw uitgaven zijn.  

**Berichten ontvangen over uw Stadjerspas** 
Wij houden je graag op de hoogte van jouw gebruik. Zijn je tegoeden bijna op? Dan krijg je een bericht van ons. Altijd handig! Natuurlijk kun je dit zelf uitzetten als je deze berichten niet wilt.  

**Zo gebruiken we jouw gegevens** 
Wij zijn natuurlijk erg voorzichtig met jouw persoonlijke gegevens. We gaan hier vertrouwelijk mee om. Wij verstrekken jouw gegevens dus ook niet aan anderen. 

**Inzicht in jouw gegevens** 
Je hebt altijd recht om je persoonlijke gegevens te bekijken, aan te passen en/of te verwijderen. Je kunt je persoonlijke gegevens die je hebt ingevuld terugvinden op je Stadjerspas account  

**Wil je meer weten of heb je vragen?** 
Bekijk de algemene privacyverklaring van de gemeente Groningen. Voor vragen kun je bellen met de gemeente Groningen via tel: 14 050.
