### ISSUE TITLE
Me records privacy: Design review

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#509]
@jamalv commented on [Mon Nov 02 2020](https://github.com/teamforus/general/issues/561)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
As a user I would like to be informed about my privacy in the me app.

Figma: https://www.figma.com/file/TQMxcPx7ANAldafD9seRsF/?node-id=1%3A80

**Comment by Myshelova** [comment]
iOS Privacy + About: https://www.figma.com/file/TQMxcPx7ANAldafD9seRsF/?node-id=70%3A300
Android Privacy + About: https://www.figma.com/file/TQMxcPx7ANAldafD9seRsF/?node-id=126%3A502
