### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by danrminds** [teamforus/me#51]
We need to implement a easier way to manage translations in the applications. 
In the web version we will use PUG/JSON files with translations and variables in the markup. 
Open for suggestions if that is possible for the mobile apps as well.

**Comment by jknnr** [comment]
We already have translations in xml files (android), Daniel will create the equivalent for iOS

**Comment by danrminds** [comment]
Can you show / call with Max to show him how to work with those and where to find?

**Comment by jknnr** [comment]
we have checked it, maybe needs more dutch specialist to see. Here are the texts

**Comment by jknnr** [comment]
@linda-90 boys say you are the best in Dutch, could you have a look? :)

**Comment by jknnr** [comment]
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">Me</string>
    <string name="blank_string"> </string>
    <string name="url"></string>


    <string name="refreshing_error_text">Refresh error</string>
    <string name="create_account">Profiel Toevoegen</string>
    <string name="restore_account">Ik heb een Me identitet</string>

    <string name="error_text">Gefaald</string>
    <string name="retry_text">Retry</string>

    <string name="exception_message_generic">Er is een toepassingsfout opgetreden</string>
    <string name="exception_message_no_connection">Er is geen internetverbinding</string>
    <string name="exception_message_user_not_found">Gebruikersgegevens kunnen niet worden opgehaald. Controleer je internetverbinding</string>


    <string name="not_empty_validation_regex">^(.*)$</string>
    <string name="not_empty_error">Veld is leeg</string>
    <string name="email_validation_regex">^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$</string>
    <string name="email_is_invalid">Veld is ongeldig</string>
    <string name="required_asterisk"><![CDATA[ <sup><small>*</small></sup> ]]></string>
    <string name="decimal_validation_regex">/^(0|[1-9]\d*)(\.\d+)?$/</string>
    <string name="decimal_validation_error">Nummer is niet geldig</string>

    <string name="property">Eigendom</string>


    <string name="navigation_drawer_open">Open navigatie </string>
    <string name="navigation_drawer_close">Close navigation </string>
    <string name="lorem_ipsum">Lorem ipsum dolor sit amet</string>
    <string name="welcome">Welkom bij Me</string>
    <string name="set_up_your_identity">Stel uw identiteit in</string>
    <string name="login">Anmelden</string>
    <string name="scan_deze_qr_code_met_een_ander_apparaat_waar_u_al_op_aangemeld_bent">Scan deze QR-Code met een ander apparaat waar u al op aangemeld bent</string>
    <string name="valuta">Valuta</string>
    <string name="bezit">Bezit</string>
    <string name="qr">Qr</string>
    <string name="records">Eigenschappen</string>

    
    <string name="lock_exit">Uitgang</string>
    <string name="lock_settings">Instellingen</string>
    <string name="lock_title">Lock Screen</string>
    <string name="lock_body">Secure lock-scherm is niet ingesteld. Als je wilt blijven werken met deze app, ga je naar Instellingen en stel je een vergrendelschermmethode in.
    </string>
  (Secure lock screen is not set up. To continue working with this app, please got to Settings and set a lock screen method.)

    <dimen name="pin_default_text_size">34sp</dimen>
    <dimen name="pin_default_button_size">60dp</dimen>
    <dimen name="pin_default_delete_button_size">24dp</dimen>
    <dimen name="pin_default_horizontal_spacing">32dp</dimen>
    <dimen name="pin_default_vertical_spacing">0dp</dimen>

    <dimen name="pin_default_dot_diameter">8dp</dimen>
    <dimen name="pin_default_dot_spacing">8dp</dimen>

    
    <string name="title_new_record">Nieuw record</string>
    <string name="title_choose_category">Kies categorie</string>
    <string name="title_choose_type">Lies Type</string>
    <string name="title_choose_text">Text</string>
    <string name="title_choose_validators">Validators</string>

    <string name="choose_the_category_text">Selecteer de categorie waaronder de nieuwe record moet worden toegevoegd</string>
    <string name="choose_the_type_text">Selecteer het type waaronder de nieuwe record moet worden toegevoegd</string>
    <string name="choose_the_value_text">Voer de waarde van de record in</string>
    <string name="choose_validators_text">Selecteer de validators, de uwe de nieuwe record moet verifiëren</string>
    <string name="venue_text">Plaats</string>

    <string name="next_step">VOLGENDE STAP</string>
    <string name="submit">SUBMIT</string>
    <string name="add_record">Voeg record toe</string>

    
    <string name="title_record_detail">Record details</string>
    <string name="title_record_detail_validators">Validators</string>
    <string name="record_detail_scan_qr">Scan deze QR-Code met een ander apparaat waar u al op aangemeld bent</string>
    <string name="button_show_qr">Toon QR</string>
    <string name="validation_request_error">Fout tijdens het verzenden van validatieaanvraag</string>
    <string name="validators_title_normal">Validators</string>
    <string name="validators_title_p2p">Peer-to-peer validaties</string>
    <string name="validators_title_empty">Je hebt nog geen validaties</string>

    
    <string name="new_account_title">New profiel</string>
    <string name="new_account_subtitle">Geef hieronder uw e-mail en informatie op. Voor registratie is een primair e-mailadres vereist</string>
    <string name="new_account_error_already_in_use">Account is al in gebruik</string>

    
    <string name="title_create_passcode">Maak een toegangscode</string>
    <string name="title_confirm_passcode">Bevestig toegangscode</string>
    <string name="title_create_identity">Even geduld aub
</string>
    <string name="subtitle_create_passcode">Maak een 4cijferige pincode aan</string>
    <string name="subtitle_create_passcode_not_match">Wachtwoorden komen niet overeen. Probeer het opnieuw</string>
    <string name="subtitle_create_identity">Identiteit creëren</string>
    <string name="subtitle_create_identity_error">Er is iets fout gegaan :(</string>

    
    <string name="subtitle_pinlock_confirm">bevestig je identiteit</string>
    <string name="subtitle_pinlock_checking">Controleren</string>
    <string name="subtitle_pinlock_error">Verkeerde toegangscode</string>

    
    <string name="wallet_title_info">Wallet informatie</string>
    <string name="wallet_current_balance">Huidig balans
</string>
    <string name="wallet_balance_fiat">~ %1$s€;    %2$s$</string>
    <string name="wallet_send">Zend</string>
    <string name="wallet_receive">Wraag</string>
    <string name="wallet_transactions_title">Transactieoverzicht</string>
    <string name="wallet_transactions_see_all">Alles zien</string>

    
    <string name="login_via_de_qr_code">login via de qr code</string>
    <string name="inloggen_met_pincode">Inloggen met pincode</string>
    <string name="inloggen_via_email">Inloggen via email</string>
    <string name="restore_by_email">Herstel per e-mail</string>
    <string name="account_restore_description">Voer uw e-mailadres in om uw inloggegevens te ontvangen</string>
    <string name="btn_continue">Doorgaan</string>
    <string name="pincode_not_confirmed">PIN is not confirmed</string>
    <string name="pincode_description">Vul deze pincode in uw profeil in</string>
    <string name="email_description">De link is naar uw e-mail verzonden. Tik erop, wacht op het succesbericht en kom bij mij terug</string>

    
    <string name="qr_validation_approved">Validatie goedgekeurd</string>
    <string name="qr_identity_restored">Identiteit hersteld</string>
    <string name="qr_unknown_type">Onbekende QR</string>
    <string name="qr_unexpected_error">Onverwachte fout</string>

    
    <string name="vouchers">Vouchers</string>
    <string name="voucher">Voucher</string>
    <string name="transactieoverzicht">Transactieoverzicht</string>
    <string name="transactieoverzicht_empty">Nog geen transacties</string>
    <string name="vouchers_no_items">Je hebt nog geen vouchers</string>
    <string name="vouchers_make_transaction">GENEREREN</string>

</resources>

**Comment by jknnr** [comment]
@maxvisser maybe will take a minute, but could you check this dutch for android?

**Comment by iNomaD** [comment]
Hello! I've updated some texts.
Here are string in [English](https://github.com/initflow/me-android/blob/development/presentation/src/main/res/values/strings.xml) and [Dutch](https://github.com/initflow/me-android/blob/development/presentation/src/main/res/values-nl/strings.xml). Please, have a look.

**Comment by jknnr** [comment]
We have made two xml files for android, with iOS its not so easy, there are many interface views, it takes special knowledge to understand what to change and where. It can result in bugs and crashes. If we need to change the texts in iOS app, better ask Daniel or me. I am closing the issue.
