### ISSUE TITLE
Proposal: Price agreement, me-app checkout

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#510]
## Context/goal: 
- [x] Clean-up zenhub proposal
- [x] write context for Lena/Linda

**Comment by maxvisser** [comment]
During acceptance test some important stuff came to light:
- price agreements (which amount gets payed out) is not visible in the app)
- There is a difference between products which are subsidizes to become free and products without a price. For products without a price we dont show the word free and should have a different text for submitting the payment

**Comment by maxvisser** [comment]
Review figma file for text/design review:
https://www.figma.com/file/OL6X0AUnpbiP8TX5dq1mU9/?node-id=20%3A205

**Comment by maxvisser** [comment]
@jamalv could  you check figma and add concept checkmark to the proposal?

**Comment by jamalv** [comment]
@maxvisser approved, great work!
