### ISSUE TITLE
Design review: price agreement, me-app checkout

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#511]
## Context/goal: 

During acceptance test some important stuff came to light:
- price agreements (which amount gets payed out) is not visible in the app)
- There is a difference between products which are subsidizes to become free and products without a price. For products without a price we dont show the word free and should have a different text for submitting the payment

https://www.figma.com/file/OL6X0AUnpbiP8TX5dq1mU9/?node-id=20%3A205

**Comment by jamalv** [comment]
@maxvisser lena asked for some more context about the variables during last refinement call. could you help her understand what it means?

**Comment by jamalv** [comment]
(maybe plan a call or add some more info in figma?)

**Comment by Myshelova** [comment]
I have a couple of questions about the problem we're trying to solve. I think the call may be great

**Comment by maxvisser** [comment]
Answered the question today
