### ISSUE TITLE
UI improvements iOS Me 0.4.1

### ISSUE THREAD

**Issue by Myshelova** [teamforus/me#516]
## Context/goal: 
Here you can find everything that needs to be fixed for the next release of the app. Scroll down and see the full task description, examples, and links. Please mark the tasks when they are finished

**Scope of works:**
+ 1 – App navigation toolbars
+ 2 – Tooltips
+ 3 – About me screen 
+ 4 – QR code modal sheet
+ 5 – Wrong icon – Product Voucher
+ 6 – Transaction history – Voucher details screen - Light mode
+ 7 – Record detail screen – Toolbar, screen scroll

**1. App navigation toolbars**
- [x] a. App navigation toolbars should be twisted and all screen content should be scrolled. We need to update all navigation bars across the App
- [x] b. Please remove all unnecessary scrolls (transactions history)
_Example:_ At the voucher details screen we should scroll all screen content, not only transactions. How this **screen scroll should look like** you can see at this example of the new concept of product voucher: https://drive.google.com/file/d/1u0NxAnCuFLp1j2n0z4wRVScz9dD0NeUt/view?usp=sharing

_Right UI for navigation toolbar:_
<img width="427" alt="Screenshot 2020-11-19 at 21 02 24" src="https://user-images.githubusercontent.com/22478043/99718063-935bb580-2aaa-11eb-94a3-6256b5be64a9.png">

_Figma prototype:_ https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1098%3A16029

_Wrong UI:_
![image](https://user-images.githubusercontent.com/22478043/99655200-b4e18080-2a5b-11eb-937c-7ae8c169c404.png)
![image](https://user-images.githubusercontent.com/22478043/99655218-b90d9e00-2a5b-11eb-9c99-ddf29e7814b3.png)
![image](https://user-images.githubusercontent.com/22478043/99655232-bd39bb80-2a5b-11eb-91f1-f0f974d0eec8.png)

- [x] **2. Tooltips**
Tooltips should be hidden after 30 sec on the screen and we're showing them just once. There no reason to show them every app opening
How to implement this see here https://github.com/teamforus/me/issues/444

**3. About Me screen** 
- [x] a. Wrong fonts and position of components. 
- [ ] b. Also, the navigation bars should be updated
- [ ] c. Make large title transitions to a standard title as people begin scrolling the content.
_Figma prototypes with comments:_ https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=2070%3A0

<img width="848" alt="Screenshot 2020-11-19 at 20 03 21" src="https://user-images.githubusercontent.com/22478043/99711723-6b685400-2aa2-11eb-93dd-54ac606a22b6.png">

**4. QR code modal sheet**
- [x] a. The modal sheet should be higher and longer. The end of the container should be at the bottom of the screen
- [x] b. Wrong UI for the text. In the app version, it looks messy. Need for updates
- [x] c. The record's QR should be named properly

_Figma prototypes with comments:_ https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1098%3A14336
<img width="508" alt="Screenshot 2020-11-19 at 20 22 28" src="https://user-images.githubusercontent.com/22478043/99713843-18dc6700-2aa5-11eb-9cfd-61b0f97752db.png">

- [x] **5. Wrong icon – Product Voucher**
Wrong icon and curved borders (oval in the current version, but the icon border should be rounded)
_Figma prototype:_ https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1098%3A16029
<img width="877" alt="Screenshot 2020-11-19 at 20 49 49" src="https://user-images.githubusercontent.com/22478043/99716805-d87ee800-2aa8-11eb-9b7c-8105af85ad13.png">

**6. Transaction history – Voucher details screen**
- [x] a. Background of the transactions history block at the light mode is missed. 
- [ ] b. Icons for the transaction statuses are missed & the logos need to be removed
- [x] c. Big spacing between buttons ant title of history block should be reduced
- [x] d. Use capitals for the caption (CREATED // ACTIVATED)
- [ ] e. Wrong statuses of transactions (what is "product voucher" status?)
_Figma prototype:_ https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1098%3A16029
<img width="447" alt="Screenshot 2020-11-19 at 21 09 12" src="https://user-images.githubusercontent.com/22478043/99718673-868b9180-2aab-11eb-9984-43989b167f40.png">

 **7. Record detail screen – Toolbar, screen scroll**
- [x] a. Wrong size for top toolbar
- [x] b. Wrong position of the back icon
- [x] c. All dividers between validations history are missed
- [x] d. All screen should be scrolled. How it should look like see at 1st task with the vouchers scroll. 
- [x] e. Make large title transitions to a standard title as people begin scrolling the content.
- [x] f. Use capitals for the SHOW QR BUTTON
- [x] g. Please remove all unnecessary scrolls (validations history)

_Figma prototype:_ https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1098%3A11364
<img width="806" alt="Screenshot 2020-11-19 at 21 49 26" src="https://user-images.githubusercontent.com/22478043/99722710-5810b500-2ab1-11eb-9bbd-c690e8e8d77a.png">

**Comment by maxvisser** [comment]
@jknnr could you create new tasks for  the things left here and close this big one?
