### ISSUE TITLE
Expired voucher UI improvements

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#517]
![image](https://user-images.githubusercontent.com/32199937/99789052-10cb0880-2b33-11eb-9fbf-f3630cc1bbb6.png)

**Comment by Myshelova** [comment]
iOS: https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1098%3A16029
<img width="747" alt="Screenshot 2020-11-20 at 20 38 10" src="https://user-images.githubusercontent.com/22478043/99842570-5eb23180-2b70-11eb-8570-0dce1b34f5d2.png">

Android: https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/?node-id=756%3A0
<img width="434" alt="Screenshot 2020-11-20 at 20 38 37" src="https://user-images.githubusercontent.com/22478043/99842611-72f62e80-2b70-11eb-8ddd-4839eb1d75bb.png">
