### ISSUE TITLE
Me privacy page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#522]
### Change description
As a user I would like to be informed about my privacy in the me app.

Figma: https://www.figma.com/file/TQMxcPx7ANAldafD9seRsF/?node-id=1%3A80

**Comment by jknnr** [comment]
@maxvisser 😛 
https://github.com/teamforus/me/issues/520

**Comment by maxvisser** [comment]
Could not find it linked to Change request in general thanks!
