### ISSUE TITLE
Me-app checkout

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#524]
## Context/goal: 
During acceptance test some important stuff came to light:

price agreements (which amount gets payed out) is not visible in the app)
There is a difference between products which are subsidizes to become free and products without a price. For products without a price we dont show the word free and should have a different text for submitting the payment

https://www.figma.com/file/OL6X0AUnpbiP8TX5dq1mU9/?node-id=168%3A5424

**Comment by maxvisser** [comment]
should be done on iOS, @maxvisser will check android

**Comment by maartenfv** [comment]
@maxvisser This is high prio. Do you have a status update?

**Comment by jamalv** [comment]
pr is here, will discuss release this afternoon with yasha

**Comment by maxvisser** [comment]
Not sure why this is assigned to me.
