### ISSUE TITLE
Implement: change "voucher info" to "Aanbod" and link to actions/aanbod

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#529]
@jamalv commented on [Tue Dec 22 2020](https://github.com/teamforus/general/issues/675)

## Task 
- [x] write user story
- [x] add figma proposal for android/iOS (currently there is no word on android do we want to change this?)

**Comment by jamalv** [comment]
Needs frontend (link to aanbod block on voucher page, in page scrolling)

Needs me app updates

**Comment by jamalv** [comment]
Can have paramater from app to know if needs to send to voucher page or directly to products list

If this parameter is there, it can be redirected to actions or product page.

**Comment by maxvisser** [comment]
@jamalv if we want to add this to release v0.5.0 we need this proposal asap :)

**Comment by jamalv** [comment]
probably only a text change in the apps "voucher info" to > "aanbod"

**Comment by jamalv** [comment]
![Screenshot 2021-01-18 at 13.18.06.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/bd7e5260-8472-48bc-b67a-5588f88be377)

**Comment by jamalv** [comment]
@jknnr

**Comment by jamalv** [comment]
Could use icon:

![Screenshot 2021-01-18 at 13.19.58.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/e1302bb0-78c9-4229-9994-234abf8e53b9)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/104914832-02ad3300-5990-11eb-84c6-07bfe6962243.png)

**Comment by maxvisser** [comment]
Icon for the tag:
https://materialdesignicons.com/icon/tag
