### ISSUE TITLE
Weird full screen error when authentication code is expired

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#536]
## Context/goal: 

<img src="https://user-images.githubusercontent.com/10818702/104744142-d190f080-574c-11eb-8ddd-3e83c54be0b2.png" height=400>

Questions:
all cases we show this error;

button text could become 'Go to signup'/'Ga verder'

**Comment by maestrovsmaster** [comment]
"Niet in behandeling", seems, it is message from server

**Comment by maxvisser** [comment]
do you catch auth error with this error screen (you know which cases it can popup?)

**Comment by maestrovsmaster** [comment]
Currently it not showing and not using, because we can't catch error condition from api.

**Comment by jknnr** [comment]
done
