### ISSUE TITLE
Vakantie overdracht

### ISSUE THREAD

**Issue by PatrickTrentelman** [teamforus/me#576]

**Comment by PatrickTrentelman** [comment]
Instellen mailresponder
 Algemeen aanspreekpunt voor vragen aanstellen zie mail responder.

**Comment by PatrickTrentelman** [comment]
@jamalv wil jij zorgen dat we worden aangemeld bij : 
 https://www.rijksinnovatiecommunity.nl/onderwerpen/community
net vorige week open gegaan, wil ik ons in hebben!!
kan alleen op uitnodiging door een overheidsfunctionaris die betrokken is bij een pilot/project ism overheid

**Comment by PatrickTrentelman** [comment]
@jamalv Wil je ons hiervoor aanmelden?
De inschrijving voor de #weekvandedienstverlening is geopend!

In de week van 20 tot en met 24 juni 2022 is de week van de dienstverlening. Een week vóór en dóór gemeenten die actief bezig zijn met dienstverlening. In het hele land vinden er in die week online en fysieke sessies plaats met als thema #dienstverlening , #digitaliseren  en de impact op #mens&organisatie. 

Gemeenten die een sessie willen organiseren kunnen zich inschrijven op https://lnkd.in/ezdeVTiS. Samen met Pleio Support en Communicatie heeft de week van de dienstverlening een site opgezet waar organisaties hun sessie kunnen registreren en in een latere fase deelnemers zich kunnen inschrijven op sessies. 

**In de week kan je een inspiratiesessie verzorgen voor je eigen gemeente of open stellen voor andere deelnemers. Je kan een ervaring delen, inhoudelijk inspireren of een complete hackathon organiseren! Kortom alles wat bijdraagt aan een betere dienstverlening voor de inwoners**.

In de komende weken verschijnen er regelmatig blogs om de ontwikkelingen onder de aandacht te brengen en praktische tips voor het organiseren en faciliteren van een sessie.

Voor vragen kan je terecht bij Roel Beurskens en Jeroen Stam

De week van de dienstverlening is een initiatief van de Gemeente Tilburg , Gemeente Wageningen, coöperatieve vereniging Dimpact en Vereniging Directeuren Publieksdiensten (VDP). Naast de VDP en Dimpact is ook het A&O fonds Gemeenten sponsor van deze week. De week wordt gevormd met o.a. presentaties, inspiratiesessies, workshops en een hackathon van gemeenten, het Rijk, koepelorganisaties, VNG en de Topkring Dienstverlening.


Prachtige kans voor een showcase!! Maar dan moeten we door een klant van ons worden aangemeld.

**Comment by PatrickTrentelman** [comment]
@maartenfv zou je willen [monitoren dat deze 2 [posts]](https://app.zenhub.com/workspaces/whole-team-5e79d635e969e6cdeeebb411/issues/teamforus/me/576) goed worden opgepakt, lijken me hele mooie kansen! ;D

**Comment by jamalv** [comment]
Issue moved to [teamforus/operations #265](https://github.com/teamforus/operations/issues/265) via [**ZenHub**](https://www.zenhub.com/)
