### ISSUE TITLE
Layout problems in provider dashboard on Android 1080 × 2400 20:9

### ISSUE THREAD

**Issue by lexlog** [teamforus/me#579]
## Prerequisites

Me app and android device with 1080 × 2400 20:9 resolution

## Description
There are layout problems in the provider dashboard 

## Steps to Reproduce (bug report)

1. Login into https://staging.forus.io/provider

**Expected behavior:** 
The page is open, all elements are visible and do not overlap

**Actual behavior:** 
Upper menu elements are overlapped, and tabs are not fit on the wideness
![image.png](https://images.zenhubusercontent.com/61f3eb266b88bef87ba3c2eb/14eb3c55-4bbf-46b1-a430-326d9de9fe3a)

**Reproduces how often:** 
All times

## Additional Information (optional)
-

**Comment by GerbenBosschieter** [comment]
@lexlog our dashboards (validator, sponsor and provider) are not mobile friendly. We want to fix this with the farewell angular project. This is where @sashooa made all the designs for

**Comment by lexlog** [comment]
aa ok, i thought about it, but decided to create it
so for now I will close it
