### ISSUE TITLE
Improve input fields in the create identity screen

### ISSUE THREAD

**Issue by jastam** [teamforus/me#58]
- don't show email error before the user is finished typing
- don't auto capital first letter of email
- do auto capital first name and last name

**Comment by maxvisser** [comment]
Is this issue for me-android or me-ios? or both?

**Comment by GerbenBosschieter** [comment]
both and it's not something I can solve to be honest. This has to be assigned to the app developers.

**Comment by iNomaD** [comment]
I've set up input types of fields:
email_field = textEmailAddress
first_name, last_name = textPersonName
bsn_field = text
phone_field = phone

The input type helps the device to turn different options for the virtual keyboard for each field. I guess it should be enough as the other options like capitalize first letter etc. depend on the keyboard settings of the Android device.

Errors are now displayed after pressing the action button.

**Comment by maxvisser** [comment]
@iNomad you can remove bsn and phone_field for now

**Comment by iNomaD** [comment]
ok

**Comment by maxvisser** [comment]
And add a confirm_email_field so its not accidently entered wrong

**Comment by jknnr** [comment]
working on it also on iOS

**Comment by jknnr** [comment]
both platforms fixed

**Comment by jknnr** [comment]
both platforms fixed

**Comment by jknnr** [comment]
fixed both platforms
