### ISSUE TITLE
E-Mail address as profile name

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#61]
Citizens dont get a prevalidated Name and Family Name. Therefore when the me app displays name and lastname it can better display the email address. 

Better fix: the me app should ask for name and last name when people authorize device

**Comment by maxvisser** [comment]
I think this is fixed on android.

**Comment by iNomaD** [comment]
Both the fullname (if provided) and email (always) are displayed at the moment.
![2018-10-22 12 56 43](https://user-images.githubusercontent.com/3989600/47287156-fba0ea00-d5f9-11e8-93e5-f775163fc784.png)

**Comment by maxvisser** [comment]
Great thanks! This also applies for iOS

**Comment by jknnr** [comment]
fixed
