### ISSUE TITLE
Buildnumbers, bundle identifiers and different environments

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#62]
As we have three environments to connect the Me app to: dev, demo and production. We need a good way to set the type of build in config of Android Studio or xcode, instead of manually editing the api link in code.

**Comment by maxvisser** [comment]
I see Android has already a debug if statement when selecting which api to use. We should investigate how to add demo to this.

**Comment by maxvisser** [comment]
Setting this up and having dev and demo in crashlytics and testflight has to be fixed for 1 nov

**Comment by jknnr** [comment]
Alright, we will have a look

**Comment by iNomaD** [comment]
@maxvisser 
What exact configs do we have for each of dev, demo and production?

**Comment by iNomaD** [comment]
@maxvisser 
@kremlinwarrior 
@jknnr 
I've solved this issue in https://github.com/teamforus/me-android/commit/5216461e8cd46455272fb962b620b1fb3f9a20d0
To build the target APK simply go to Android Studio -> Build -> Select Build Variant -> choose the one you need from the list. And you could also see the current version in the _Profile/About_ section of the app.
![2018-10-22 16 49 36](https://user-images.githubusercontent.com/3989600/47297187-13d63080-d61d-11e8-95c4-2537a0290ce7.png)

**Comment by jknnr** [comment]
@maxvisser for this issue to be solved on iOS we need a developer access. Can you help?

**Comment by maxvisser** [comment]
@jknnr i dont know enough about itunesconnect maybe gerben can help?

**Comment by maxvisser** [comment]
@gerbenbosschieter can you also test the android build variants if this works for you?

**Comment by maxvisser** [comment]
Hi iNomad, can you build dev and demo and put them in your latest release on me android?

**Comment by iNomaD** [comment]
ok

**Comment by GerbenBosschieter** [comment]
@jknnr I can help with that :)

**Comment by iNomaD** [comment]
@maxvisser
Published them:
https://github.com/teamforus/me-android/releases/tag/v0.0.4-dev
https://github.com/teamforus/me-android/releases/tag/v0.0.4-demo

**Comment by jknnr** [comment]
fixed both platforms
