### ISSUE TITLE
Improve qr scanner screen

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#64]
**Is your feature request related to a problem? Please describe.**
Last year's voucher scanner included a short description and a slightly better looking voucher scanner then the current one.

### Old:
<img src="https://user-images.githubusercontent.com/30194799/47257687-523ee480-d491-11e8-9d1d-aa5f172f86cb.png" width="20%" height="20%">

### New:
<img src="https://user-images.githubusercontent.com/30194799/47257754-c9747880-d491-11e8-9d79-f0661dfa8d2f.jpeg" width="20%" height="20%">

**Describe the solution you'd like**
Update the current scanner to look better. :)

**Comment by jamalv** [comment]
We can start simple but extend the screen later. Some inspiration:

<img src="https://user-images.githubusercontent.com/30194799/47257866-b4004e00-d493-11e8-9562-8b4e1ae943fc.jpeg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/30194799/47257875-ddb97500-d493-11e8-8bf4-9df5514ac9ab.jpeg" width="40%" height="40%">

**Comment by maxvisser** [comment]
Great feature request! I think adding some more context to how the interaction is within the me app; it will help.

**Comment by jknnr** [comment]
improved
