### ISSUE TITLE
Remove the profile button from the voucher screen.

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#65]
**Is your feature request related to a problem? Please describe.**
Currently at the voucher screen, the profile button is shown at two places:

<img src="https://user-images.githubusercontent.com/30194799/47258641-7ce36a00-d49e-11e8-82f8-dea5be244dd2.png" width="40%" height="40%">

**Describe the solution you'd like**
We can hide/remove it from the top right for now.

**Describe alternatives you've considered**
Later, when the voucher and records screens get more extensive, the icons can be re-added to the top right. The profile will not have its own tab anymore by then.

**Comment by jknnr** [comment]
done
