### ISSUE TITLE
Screen for accepting a payment request

### ISSUE THREAD

**Issue by danrminds** [teamforus/me#66]
Design for Android and iOS:

We need a screen to accept a payment request:

**Description**
When a provider scans a voucher shown on a Me App - he will introduce information about amount.
The requester will get a push notification to accept the payment. 
The screen will display:

Provider (shop name)
Amount
Voucher / fund name

Accept / Decline options

**Comment by maxvisser** [comment]
@jknnr this is the main use case for a citizen to download the me app. As it will help with security: the citizen accepting each payment with a pin code.

**Comment by maxvisser** [comment]
@danrminds can this only be the case for vouchers on budget base. As you already gave permission within the webshop to retract the amount from your voucher. This way product vouchers for sport clubs etc can still be mailed and it doesnt need direct consent from citizen

**Comment by jknnr** [comment]
iOS design is ready, Daniel is working on the frontend. Backend will be ready in the next two days

**Comment by maxvisser** [comment]
can you put the design in issue?

**Comment by maxvisser** [comment]
In the current version when doing a payment the shopkeeper can't see the voucher name at all. How is this now implemented?

**Comment by jknnr** [comment]
<img width="630" alt="screen shot 2018-10-26 at 10 14 01" src="https://user-images.githubusercontent.com/32199937/47556065-bb00e380-d90d-11e8-9ed2-83690a7bb6fc.png">
