### ISSUE TITLE
Implement fingerprint authentication

### ISSUE THREAD

**Issue by TomForus** [teamforus/me#7]
- [ ] Implement TouchID on iOS
- [ ] Implement [Fingerprint Authentication]( https://developer.android.com/about/versions/marshmallow/android-6.0.html#fingerprint-authentication) on Android

**Comment by maxvisser** [comment]
Both android version and iOS version will be enabled by pincode authentication. Fingerprint scanner is a feature that can be implemented after august. If this becomes relevant again, we can reopen it.
