### ISSUE TITLE
Login trough email: link doesn't work

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#72]
When clicking the link in the email, I get this error:

![img_2836](https://user-images.githubusercontent.com/30194799/47616940-1f18d880-dac3-11e8-8bf7-33b1053b47bc.png)

**Comment by maxvisser** [comment]
@iNomaD @danieltcacenco Can you check this yourselves?

**Comment by jknnr** [comment]
on it

**Comment by jknnr** [comment]
fixed
