### ISSUE TITLE
Voucher "previews" should be the actual code

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#73]
Currently when viewing a voucher, you get a fake one. Instead, it should be a miniature version of the actual voucher. Otherwise the inconsistency can cause confusion. Also, it seems lazy ;)

![img_2837](https://user-images.githubusercontent.com/30194799/47617026-14127800-dac4-11e8-9801-6cadba821a00.png)

**Comment by maxvisser** [comment]
does clicking it already open the qr code?

**Comment by jamalv** [comment]
yes

**Comment by jknnr** [comment]
This screen is going through the transition to new design. We are implementing generic actions for "show qr-code" function cause it was not obvious to click the qr-code icon. The voucher preview will now contain the icon of fund or provider.

**Comment by jknnr** [comment]
<img width="260" alt="screen shot 2018-10-28 at 17 39 57" src="https://user-images.githubusercontent.com/32199937/47618883-82f9cc00-dad8-11e8-9d46-7db9e51664c3.png">

**Comment by jamalv** [comment]
Alternative approach: when you open the voucher screen, the "my qr-code" panel automatically expands. When you want to make room to view your transactions you can hide it.

The main reason for somebody to open a voucher, will be to show the qr code to the shopkeeper, we should make it visible, and not hide it.

**Comment by jknnr** [comment]
This one is fixed by the way:)
