### ISSUE TITLE
iOS App Store inconsistencies

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#74]
App is live in: https://itunes.apple.com/nl/app/me-forus/id1422610676

The subtitle is incorrect "MeApp". If possible it can be kept empty.
<img width="212" alt="screenshot 2018-10-29 at 21 09 46" src="https://user-images.githubusercontent.com/30194799/47677423-5967a000-dbbf-11e8-9b05-18248a11a0f5.png">

<img width="279" alt="screenshot 2018-10-29 at 21 09 51" src="https://user-images.githubusercontent.com/30194799/47677522-a64b7680-dbbf-11e8-9da6-cc02c7f2fc6b.png">

**Comment by GerbenBosschieter** [comment]
Can only do this with next release, and Ofcourse I will :)

**Comment by maxvisser** [comment]
https://github.com/teamforus/me-ios/commit/8b87018b6e44d7fb38a64c79ef4fec7dad6a5a75
