### ISSUE TITLE
No info when tapping 'over me' in app version 0.0.4

### ISSUE THREAD

**Issue by nanningdejong** [teamforus/me#75]
## Prerequisites

1. iPhone SE
2. App verion 0.0.4

## Description

No info when tapping 'over me' in profiel-tab; no text is visible, only the x-closing button.

![image-1](https://user-images.githubusercontent.com/36294795/47922587-b44b1100-deb7-11e8-96a5-4e2fbf5e61e1.jpg)

**Comment by jknnr** [comment]
fixed
