### ISSUE TITLE
Add explanation on how to give or re-give permission to the QR code scanner

### ISSUE THREAD

**Issue by maartenfv** [teamforus/me#78]
Once the initial question has been asked regarding the permission for the use of the camera by the app has been declined, it is hard for non-technical users to find out why they see a black screen on the scanner page. 

It could show something like "learn how to give the app access to the camera".

**Comment by maxvisser** [comment]
Go to settings > apps > select Me > select permission > give right to camera.

**Comment by jamalv** [comment]
I believe it is possible to check for camera permissions, make a popup that states this feature doesn't work without camera access, and send the user straight to that settings page when they click okay.
