### ISSUE TITLE
No vouchers

### ISSUE THREAD

**Issue by maartenfv** [teamforus/me#79]
"je hebt nog geen vouchers"/"You don't have any vouchers yet" is a message that gives people hope. However the app does not explain how to get a voucher.

Some information on how to use the app and linking to the related webpages could help the user understand how to proceed.

**Comment by jamalv** [comment]
Related to: https://github.com/teamforus/me/issues/63

**Comment by maxvisser** [comment]
I like maarten's suggestion to add a link to https://zuidhorn.forus.io/me/ on voucher page

**Comment by maxvisser** [comment]
I will close this issue in favor of https://github.com/teamforus/me/issues/63
