### ISSUE TITLE
Authorisation code crash

### ISSUE THREAD

**Issue by jamalv** [teamforus/me#80]
## Prerequisites

1. iOS app 0.0.5(3) connected to dev environment
2. Access to an account (for example demo@forus.io)
3. Be logged in to the webshop
4. Fresh install of the app (not logged in)

## Description

When setting a passcode after logging in trough the webshop, the app crashes.

## Steps to Reproduce (bug report)

1. Log in to the webshop
2. Authorise device
3. Go to profile, set pincode (I used 0000)

**Expected behavior:** pincode is set

**Actual behavior:** crash

**Reproduces how often:** 100%

**Comment by jknnr** [comment]
fixed
