### ISSUE TITLE
Distribute demo to stakeholders iOS/Android

### ISSUE THREAD

**Issue by TomForus** [teamforus/me#9]
# Install the Demo

- [x] Make installer available for android
- [x] Compile for iOS
    - [x] Add to TestFlight

## Functional Design (Enhancement)

- [x] To make the demo for the presentation
- [x] Make a stable version for the Back-end of the demo
- [x] Host the app and the Kindpakket demo version on a live server
- [x] Compile the demo for the devices of the stakeholders.

**User Story:** The demo should work without flaws so it can be presented.

## Additional Information
@danrminds and @dev-weget will work on this.

**Comment by danrminds** [comment]
The demo now is hosted on our (RocketMinds) server. Should we move it to a live server of Forus?

**Comment by jamalv** [comment]
yea that would be great, something like medemo.forus.io ? @maxvisser ?

**Comment by danrminds** [comment]
Now the demo is hosted on:

demo.kindpakket.forus.io
demo.vote.kindpakket.forus.io
demo.api.kindpakket.forus.io
